### ISSUE TITLE
Trouble compiling Cantaloupe

### ISSUE THREAD

**Issue by devanonyme** [medusa-project/cantaloupe#109]
Hello, 

I wanted to compile cantaloupe so that I can help investigate issues (I have one with cors and I wanted to change the default * to our our test domain to see the behavior with one problem I have).

I did a rebuild from develop branch and also release 3.3 and I get (even if replace the war inside the working release I have instead of trying to use the build from target folder) :

Anything obvious that could be missing?

java -Dcantaloupe.config=cantaloupe.properties -Xmx2g -jar Cantaloupe-3.3.war
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/configuration/ConversionException
        at edu.illinois.library.cantaloupe.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:33)
        at edu.illinois.library.cantaloupe.StandaloneEntry.main(StandaloneEntry.java:89)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.configuration.ConversionException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

I suspect an error in config loading as I get the same error if I give an non-existing file name (I also tried with full path to properties file (forward and backward slashes (on windows)).

Any idea?

**Comment by devanonyme** [comment]
The solution was simple, I had to double escape the path (on windows) :

 java -Dcantaloupe.config=c:\\DEVEL\\cantaloupe\\cantaloupe.properties.sample -Xmx2g -jar Cantaloupe-3.3.war
