### ISSUE TITLE
Error - does not support the JPEG source format

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#126]
Hello,
I try to open JPEG image with ImageMagickProcessor and get this error,

`edu.illinois.library.cantaloupe.processor.UnsupportedSourceFormatException: ImageMagickProcessor does not support the JPEG source format
	at edu.illinois.library.cantaloupe.processor.AbstractProcessor.setSourceFormat(AbstractProcessor.java:45)
	at edu.illinois.library.cantaloupe.processor.ProcessorFactory.getProcessor(ProcessorFactory.java:59)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:523)
	at org.restlet.resource.ServerResource.get(ServerResource.java:742)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:617)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:678)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:356)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1043)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
`
Please help !

**Comment by prilia** [comment]
Sorry , wrong path.

**Comment by prilia** [comment]
Sorry , wrong path to imagemagic !
