### ISSUE TITLE
Startup fails with exception in initializer code

### ISSUE THREAD

**Issue by imoutsatsos** [medusa-project/cantaloupe#129]
I have build the Cantaloupe-3.4.SNAPSHOT from code and deployed to a Windows 2012 server. However, the server hungs with an initializer error.

E:\IMAGING\Cantaloupe>java -Dcantaloupe.config=E:\IMAGING\Cantaloupe\cantaloupe.properties -Xmx2g -jar Cantaloupe-3.4-SNAPSHOT.war
Loading config file: E:\IMAGING\Cantaloupe\cantaloupe.properties
2017-07-13 13:28:33.243:INFO::main: Logging initialized @413ms to org.eclipse.jetty.util.log.StdErrLog
2017-07-13 13:28:33.477:INFO:oejs.Server:main: jetty-9.4.z-SNAPSHOT
2017-07-13 13:28:43.696:INFO:oejs.AbstractConnector:main: Started ServerConnector@5a6a9415{HTTP/1.1,[http/1.1, h2c]}{0.0
.0.0:8182}
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.eclipse.jetty.http.MimeTypes$Type.<init>(MimeTypes.java:102)
        at org.eclipse.jetty.http.MimeTypes$Type.<clinit>(MimeTypes.java:58)
        at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:190)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:769)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:452)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:419)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at edu.illinois.library.cantaloupe.WebServer.start(WebServer.java:303)
        at edu.illinois.library.cantaloupe.StandaloneEntry.main(StandaloneEntry.java:112)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.eclipse.jetty.http.PreEncodedHttpField.<clinit>(PreEncodedHttpField.java:71)
        ... 15 more

**Comment by adolski** [comment]
I think I'm not packaging Jetty correctly. For a quick fix, if you unzip the war file and combine the two files in META-INF/services into one (the name doesn't matter), and then re-zip it, it should work. But I need to figure out how to do this with Maven.

**Comment by imoutsatsos** [comment]
Thanks Alex;
The workaround you suggested works!

**Comment by imoutsatsos** [comment]
I'm wondering if there is a regression issue. I the latest develop branch, I still get the same error. Just a heads up. I will try the trick above.

**Comment by adolski** [comment]
Hmmm,`mvn clean package -DskipTests` is producing a runnable WAR for me in macOS. I'll try in Windows.

**Comment by imoutsatsos** [comment]
Sorry, I think I messed up the repo update! After rebuilding all is well! I hope I did not waste too much of your time :-(
