### ISSUE TITLE
GraphicsMagick Processor Issue

### ISSUE THREAD

**Issue by sanfordd** [medusa-project/cantaloupe#135]
I'm encountering an issue using GraphicsMagick along a http resolver with a filesystem cache. The behavior should be to cache the image locally and then call GraphicsMagick, but GraphicsMagick appears to be causing an error before the local disk lookup can occur.
With issue #62 in mind, an attempt was made give a direct path to GraphicsMagick and the user account Cantaloupe runs in, Tomcat, was able to run a gm command.

```
[http-bio-8080-exec-7] 34mINFO 0;39m 36me.i.l.c.r.AbstractResource0;39m - doInit(): handling GET http://ww.xx.yy.zz:8080/iiif/2/
t722h924t%2Ffiles%2F8d945d0d-98df-437c-8ebe-b4f334a07bcd/info.json
14:10:13.017 [http-bio-8080-exec-7] 39mDEBUG0;39m 36me.i.l.c.r.i.v.InformationResource0;39m - Identifier requested: t722h924t%2Ffiles%2F8d945d0d
-98df-437c-8ebe-b4f334a07bcd / decoded: t722h924t/files/8d945d0d-98df-437c-8ebe-b4f334a07bcd / slashes substituted: t722h924t/files/8d945d0d-98d
f-437c-8ebe-b4f334a07bcd
14:10:13.018 [http-bio-8080-exec-7] 39mDEBUG0;39m 36me.i.l.c.s.RubyScriptEngine0;39m - invoke(Cantaloupe::HttpResolver::get_url): exec time: 1 m
sec
14:10:13.024 [http-bio-8080-exec-7] 39mDEBUG0;39m 36me.i.l.c.s.RubyScriptEngine0;39m - invoke(Cantaloupe::HttpResolver::get_url): exec time: 1 m
sec
14:10:13.024 [http-bio-8080-exec-7] 34mINFO 0;39m 36me.i.l.c.r.HttpResolver0;39m - Resolved t722h924t/files/8d945d0d-98df-437c-8ebe-b4f334a07bcd to http://aa.bb.cc.dd:8080/fedora/rest/prod/t7/22/h9/24/t722h924t/files/8d945d0d-98df-437c-8ebe-b4f334a07bcd
14:10:13.035 [http-bio-8080-exec-7] 1;31mERROR0;39m 36mo.r.C.WebApplication0;39m - Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request

        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:539)
        at org.restlet.resource.ServerResource.get(ServerResource.java:742)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:617)
        at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:678)
        at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:356)
        at org.restlet.resource.ServerResource.handle(ServerResource.java:1043)
        at org.restlet.resource.Finder.handle(Finder.java:236)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
        at org.restlet.Application.handle(Application.java:385)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.Component.handle(Component.java:408)
        at org.restlet.Server.handle(Server.java:507)
        at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: edu.illinois.library.cantaloupe.processor.UnsupportedSourceFormatException: GraphicsMagickProcessor does not support the TIFF source format
        at edu.illinois.library.cantaloupe.processor.AbstractProcessor.setSourceFormat(AbstractProcessor.java:45)
        at edu.illinois.library.cantaloupe.processor.ProcessorFactory.getProcessor(ProcessorFactory.java:59)
        at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGet(InformationResource.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:523)
        ... 59 common frames omitted
```

**Comment by adolski** [comment]
Hi,

Do you see support for TIFF in the output of `gm version`?

**Comment by sanfordd** [comment]
I do see TIFF as yes.

**Comment by adolski** [comment]
Would you mind pasting your `gm version` output?

**Comment by sanfordd** [comment]
Not a problem at all,

```
GraphicsMagick 1.3.26 2017-07-04 Q8 http://www.GraphicsMagick.org/
Copyright (C) 2002-2017 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe       yes
  Large Files (> 32 bit)   yes
  Large Memory (> 32 bit)  yes
  BZIP                     yes
  DPS                      no
  FlashPix                 no
  FreeType                 yes
  Ghostscript (Library)    no
  JBIG                     yes
  JPEG-2000                yes
  JPEG                     yes
  Little CMS               yes
  Loadable Modules         no
  OpenMP                   yes (201107)
  PNG                      yes
  TIFF                     yes
  TRIO                     no
  UMEM                     no
  WebP                     no
  WMF                      yes
  X11                      yes
  XML                      yes
  ZLIB                     yes

Host type: x86_64-unknown-linux-gnu

Configured using the command:
  ./configure 

Final Build Parameters:
  CC       = gcc -std=gnu99
  CFLAGS   = -fopenmp -g -O2 -Wall -pthread
  CPPFLAGS = -I/usr/include/freetype2 -I/usr/include/libxml2
  CXX      = g++
  CXXFLAGS = -pthread
  LDFLAGS  = -L/usr/lib/x86_64-linux-gnu
  LIBS     = -ljbig -llcms2 -ltiff -lfreetype -ljasper -ljpeg -lpng12 -lwmflite -lXext -lSM -lICE -lX11 -llzma -lbz2 -lxml2 -lz -lm -lgomp -lpthread
```

**Comment by adolski** [comment]
I'm able to reproduce this when I set `GraphicsMagickProcessor.path_to_binaries` to an invalid value. My `gm` is in `/usr/local/bin`, so if I set it to that, it works. But `/usr/local/bin/gm` would _not_ work, if that's what you tried.

If that's the issue, then the error message ("GraphicsMagickProcessor does not support the TIFF source format") is misleading and I need to clean it up.

**Comment by sanfordd** [comment]
That was definitely the issue, setting it to the location caused it to recognize the processor.

**Comment by adolski** [comment]
Excellent!
