### ISSUE TITLE
Instance is frozen error

### ISSUE THREAD

**Issue by jcoyne** [medusa-project/cantaloupe#157]
```
java.io.IOException: java.lang.IllegalStateException: Instance is frozen.
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:126)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:191)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:188)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Instance is frozen.
	at edu.illinois.library.cantaloupe.operation.Rotate.addDegrees(Rotate.java:37)
	at edu.illinois.library.cantaloupe.processor.AbstractJava2DProcessor.postProcess(AbstractJava2DProcessor.java:182)
	at edu.illinois.library.cantaloupe.processor.KakaduProcessor.process(KakaduProcessor.java:319)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:163)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:124)
	... 27 common frames omitted
```

**Comment by adolski** [comment]
One step ahead of you: 8f4255f
