### ISSUE TITLE
java.lang.NoClassDefFoundError: edu/illinois/library/cantaloupe/SomeClassName$1

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#170]
Hi,
I started to get this error, but after cantaloupe restart it's working fine.
Please help !
```

2017-11-12 12:09:02,071 ERROR [qtp728890494-13] o.r.C.Server [Slf4jLogger.java:230] An exception occurred writing the response entity
java.lang.NoClassDefFoundError: edu/illinois/library/cantaloupe/operation/Crop$1
        at edu.illinois.library.cantaloupe.operation.Crop.applyOrientation(Crop.java:91)
        at edu.illinois.library.cantaloupe.processor.imageio.AbstractImageReader.readRendered(AbstractImageReader.java:513)
        at edu.illinois.library.cantaloupe.processor.imageio.ImageReader.readRendered(ImageReader.java:277)
        at edu.illinois.library.cantaloupe.processor.JaiProcessor.process(JaiProcessor.java:138)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:160)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:102)
        at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
        at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
        at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
        at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:191)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by adolski** [comment]
Hi @prilia,

When the application is started in standalone mode, Jetty unpacks some stuff into a subdirectory of `java.io.tmpdir`, which is usually the system temp dir. The operating system will clean this out periodically, and when it gets cleaned out while the application is running, files go missing.

The solution is to configure your OS to clean out the temp dir less often or only at boot/shutdown.

In 3.4 you'll also be bale to use a `temp_pathname` config key to use a different temp dir and bypass the system temp dir cleaning mechanism.

**Comment by prilia** [comment]
what is the path for the folder n 3.3 ?

**Comment by adolski** [comment]
It's whatever `java.io.tmpdir` is set to. In Linux it's often `/tmp`.

**Comment by Eyal-R** [comment]
> Jetty unpacks some stuff into a **subdirectory** of java.io.tmpdir
What is the subdirectory? I can disable the cleaning only for that subdirectory instead of the whole Linux temp dir..

**Comment by adolski** [comment]
> What is the subdirectory? I can disable the cleaning only for that subdirectory instead of the whole Linux temp dir..

At startup (in standalone mode) you'll see something like:


2017-11-16 11:54:37.271:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@1ffaf86{/,file://**/private/var/folders/86/n7hhg0xd5vs181620161k_6h0000gn/T/jetty-0.0.0.0-8182-Cantaloupe-3.3.3.war-_-any-2795990162039970178.dir**/webapp/,AVAILABLE}{/Volumes/Data/alexd/NoBackup/Cantaloupe-3.3.3/Cantaloupe-3.3.3.war}

The bold part is Jetty's temp dir.

**Comment by adolski** [comment]
This temp file stuff was mentioned briefly in the [deployment section](https://medusa-project.github.io/cantaloupe/manual/3.3/deployment.html) of the user manual, but it was under a heading called "operating system" for some reason, so I changed it to "temporary files" to hopefully make it more noticeable.
