### ISSUE TITLE
JPG tiles error - JaiProcessor, Java2dProcessor

### ISSUE THREAD

**Issue by prilia** [medusa-project/cantaloupe#175]
Hi, 
Cantaloupe-3.3.1 return request for full image without errors, if there is a tile request, it's error with this log:
```
2017-11-21 16:15:28,873 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:149] invoke(Cantaloupe::FilesystemResolver::get_pathname): cache hit (skipping invocation)
2017-11-21 16:15:28,873 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:127] invoke(Cantaloupe::FilesystemResolver::get_pathname): exec time: 0 msec
2017-11-21 16:15:28,890 INFO [qtp728890494-16] e.i.l.c.r.SourceImageWrangler [SourceImageWrangler.java:117] FileResolver -> FileProcessor connection between FilesystemResolver and JaiProcessor
2017-11-21 16:15:28,892 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:149] invoke(Cantaloupe::FilesystemResolver::get_pathname): cache hit (skipping invocation)
2017-11-21 16:15:28,892 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:127] invoke(Cantaloupe::FilesystemResolver::get_pathname): exec time: 1 msec
2017-11-21 16:15:28,903 INFO [qtp728890494-16] e.i.l.c.r.FilesystemResolver [FilesystemResolver.java:89] Resolved NOWM-XX-XX-XX-STARTFL/operational_storage/derivative_copies/2017/03/01/file_73/V1-FL45726172.jpg to /operational_storage/derivative_copies/2017/03/01/file_73/V1-FL45726172.jpg
2017-11-21 16:15:28,910 DEBUG [qtp728890494-16] e.i.l.c.p.i.AbstractImageReader [AbstractImageReader.java:116] createReader(): ignoring metadata? true
2017-11-21 16:15:28,911 DEBUG [qtp728890494-16] e.i.l.c.p.i.AbstractImageReader [AbstractImageReader.java:121] createReader(): using com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader
2017-11-21 16:15:29,346 DEBUG [qtp728890494-16] e.i.l.c.r.AbstractResource [AbstractResource.java:648] readInfo(): read from NOWM-XX-XX-XX-STARTFL/operational_storage/derivative_copies/2017/03/01/file_73/V1-FL45726172.jpg in 442 msec
2017-11-21 16:15:29,348 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:149] invoke(Cantaloupe::authorized?): cache hit (skipping invocation)
2017-11-21 16:15:29,348 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:127] invoke(Cantaloupe::authorized?): exec time: 1 msec
2017-11-21 16:15:29,349 DEBUG [qtp728890494-16] e.i.l.c.r.AbstractResource [AbstractResource.java:272] addNonEndpointOperations(): redactions are disabled; skipping.
2017-11-21 16:15:29,350 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:149] invoke(Cantaloupe::overlay): cache hit (skipping invocation)
2017-11-21 16:15:29,351 DEBUG [qtp728890494-16] e.i.l.c.s.RubyScriptEngine [RubyScriptEngine.java:127] invoke(Cantaloupe::overlay): exec time: 1 msec
2017-11-21 16:15:29,351 DEBUG [qtp728890494-16] e.i.l.c.r.AbstractResource [AbstractResource.java:192] Base URI assembled from request: http://172.0.12.154:4343
2017-11-21 16:15:29,352 DEBUG [qtp728890494-16] e.i.l.c.r.AbstractResource [AbstractResource.java:648] readInfo(): read from NOWM-XX-XX-XX-STARTFL/operational_storage/derivative_copies/2017/03/01/file_73/V1-FL45726172.jpg in 0 msec
2017-11-21 16:15:29,813 DEBUG [qtp728890494-16] e.i.l.c.p.JAIUtil [JAIUtil.java:258] scaleImageUsingSubsampleAverage(): width: 16.639141205615193%; height: 16.657027183342972%
2017-11-21 16:15:30,003 ERROR [qtp728890494-16] o.r.C.Server [Slf4jLogger.java:230] An exception occurred writing the response entity
java.io.IOException: java.lang.UnsupportedOperationException: Progressive output not supported
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:120)
        at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
        at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
        at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
        at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:191)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: Progressive output not supported
        at javax.imageio.ImageWriteParam.setProgressiveMode(ImageWriteParam.java:830)
        at edu.illinois.library.cantaloupe.processor.imageio.JPEGImageWriter.getWriteParam(JPEGImageWriter.java:98)
        at edu.illinois.library.cantaloupe.processor.imageio.JPEGImageWriter.write(JPEGImageWriter.java:160)
        at edu.illinois.library.cantaloupe.processor.imageio.ImageWriter.write(ImageWriter.java:90)
        at edu.illinois.library.cantaloupe.processor.JaiProcessor.process(JaiProcessor.java:235)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:160)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:118)
        ... 30 common frames omitted

```
properties: https://drive.google.com/open?id=1WVb7g7X-meK_xWE3tFleBHJX6VoHn0bP
images for download: https://drive.google.com/drive/folders/1SVeZrjqE9auvOc1qZvapDBNxhMzhvP_B?usp=sharing
image with error when request is for a tile :
![v1-fl45726172](https://user-images.githubusercontent.com/2115212/33081680-8b025c8e-cee3-11e7-957b-a67ad0cd0538.jpg)
no error, for full and for tile
![working](https://user-images.githubusercontent.com/2115212/33081693-962f6192-cee3-11e7-996c-30c29728b99f.jpg)

**Comment by adolski** [comment]
> `2017-11-21 16:15:28,911 DEBUG [qtp728890494-16] e.i.l.c.p.i.AbstractImageReader [AbstractImageReader.java:121] createReader(): using com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader`

This line tells me you have a mediaLib accelerator JAR on your classpath somewhere. Is that the case? If so, I guess the JPEG writer doesn't support progressive output, so try setting `processor.jpg.progressive = false` in the config file.

(Full requests aren't causing an error here because they are streamed through without going through a writer.)

**Comment by prilia** [comment]
Hi,
I am using processor.jpg.progressive = false
Please take a look:
properties: https://drive.google.com/open?id=1WVb7g7X-meK_xWE3tFleBHJX6VoHn0bP
images for download: https://drive.google.com/drive/folders/1SVeZrjqE9auvOc1qZvapDBNxhMzhvP_B?usp=sharing

The problem is that a huge amount of images are working well, but some are not.
Can you try my images on your installation ?

Thank you !

**Comment by adolski** [comment]
> 2017-11-21 16:15:28,911 DEBUG [qtp728890494-16] e.i.l.c.p.i.AbstractImageReader [AbstractImageReader.java:121] createReader(): using com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader

`com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReader` is contained in an ImageIO plugin that is not one of the standard plugins (it doesn't ship with the JRE) and it's not included in Cantaloupe. It has to be coming from somewhere else. Either it's installed on the classpath somewhere, or it's bundled in another application running in the same container. This plugin is the problem and it needs to be removed.

After it's removed, you'll see this instead:

> 09:35:22.850 [qtp1349277854-26] DEBUG e.i.l.c.p.i.AbstractImageReader - createReader(): using com.sun.imageio.plugins.jpeg.JPEGImageReader

And then you'll find that `V1-FL45726172.jpg` works without any issues. 😄
