### ISSUE TITLE
Content is not allowed in prolog.

### ISSUE THREAD

**Issue by mcreece** [medusa-project/cantaloupe#191]
I'm attempting to the the KakaduProcessor to work with .jp2 files and I'm running into the following error:

[Fatal Error] :1:1: Content is not allowed in prolog.
19:19:47.476 [http-bio-8080-exec-3] ^[[1;31mERROR^[[0;39m ^[[36mo.r.C.RestletApplication^[[0;39m - Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the r
equest
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
        at org.restlet.resource.ServerResource.get(ServerResource.java:723)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
        at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)
        at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
        at org.restlet.resource.ServerResource.handle(ServerResource.java:1020)
        at org.restlet.resource.Finder.handle(Finder.java:236)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
        at org.restlet.Application.handle(Application.java:385)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.Component.handle(Component.java:408)
        at org.restlet.Server.handle(Server.java:507)
        at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Content is not allowed in prolog.
        at edu.illinois.library.cantaloupe.processor.KakaduProcessor.readImageInfo(KakaduProcessor.java:280)
        at edu.illinois.library.cantaloupe.cache.InfoService.readInfo(InfoService.java:234)
        at edu.illinois.library.cantaloupe.cache.InfoService.getOrReadInfo(InfoService.java:166)
        at edu.illinois.library.cantaloupe.cache.CacheFacade.getOrReadInfo(CacheFacade.java:67)
        at edu.illinois.library.cantaloupe.resource.AbstractResource.getOrReadInfo(AbstractResource.java:385)
        at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGet(InformationResource.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
        ... 55 common frames omitted
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at edu.illinois.library.cantaloupe.processor.KakaduProcessor.readImageInfoDocument(KakaduProcessor.java:323)
        at edu.illinois.library.cantaloupe.processor.KakaduProcessor.readImageInfo(KakaduProcessor.java:236)
        ... 65 common frames omitted

This is occurring right after and attempt to invoke kdu_jp2info =>  Invoking /home/vagrant/kakadu/kdu_jp2info -i /home/vagrant/images/image.jp2 -siz

I'm able to manually run kdu_jp2info on the .jp2 and get a response of: 

<JP2_family_file>
  <ftyp name="file-type box" header="8" body="12" pos="12">
    <brand> "jp2_" 0x6A703220 </brand>
    <minor_version> 0 </minor_version>
    <compatible_brand> "jp2_" 0x6A703220 </compatible_brand>
  </ftyp>
  <jp2h name="JP2-header box" header="8" body="63" pos="32">
    <ihdr name="image-header box" header="8" body="14" pos="40"></ihdr>
    <colr name="colour box" header="8" body="7" pos="62"></colr>
    <res_ name="resolution box" header="8" body="18" pos="77">
      <resd name="display-resolution box" header="8" body="10" pos="85"></resd>
    </res_>
  </jp2h>
  <jp2c name="contiguous-codestream box" header="8" body="rubber" pos="103">
    <codestream>
      <width> 3512 </width>
      <height> 2320 </height>
      <components> 3 </components>
      <tiles> 1 </tiles>
      <SIZ>
        Sprofile=PROFILE2
        Sextensions=0
        Scap=no
        Ssize={2320,3512}
        Sorigin={0,0}
        Stiles={2320,3512}
        Stile_origin={0,0}
        Scomponents=3
        Ssigned=no,no,no
        Sprecision=8,8,8
        Ssampling={1,1},{1,1},{1,1}
      </SIZ>
    </codestream>
  </jp2c>
</JP2_family_file>

Any ideas?

**Comment by adolski** [comment]
Hi @mcreece,

I've seen this error before (a long time ago) and at the time it was caused by the XML parser not liking the leading whitespace in the output of kdu_jp2info. It also seemed to be platform-dependent. Trimming the XML string before giving it to the parser seemed to solve that, though:

https://github.com/medusa-project/cantaloupe/blob/51c2a470456eb118484d9db34a0818d1a1a835df/src/main/java/edu/illinois/library/cantaloupe/processor/KakaduProcessor.java#L307

But the fact that it's happening again leads me to wonder if the kdu_jp2info output is being read into a string with the wrong encoding, which might affect the trimming:

https://github.com/medusa-project/cantaloupe/blob/51c2a470456eb118484d9db34a0818d1a1a835df/src/main/java/edu/illinois/library/cantaloupe/processor/KakaduProcessor.java#L181

**Comment by mcreece** [comment]
I think this had to do with and error in my LD_LIBRARY_PATH environment variable...after clearing and resetting I got it working. Thanks!
