### ISSUE TITLE
Failure after deleting a zero-byte file?

### ISSUE THREAD

**Issue by RussellMcOrmond** [medusa-project/cantaloupe#205]
This is an intermittent problem, and if I try to load the same image again the problem doesn't happen.  This might be a race condition.

I see the problem with source being .tif (using JaiProcessor #185) and .jpg (using fallback of Java2dProcessor), so the problem isn't specific to a processor.

A 0-length file is written, detected, and deleted.  There is then a failure after the delete.

```
2018-02-23T15:01:25.387327598Z 15:01:25.387 [qtp1634198-18] DEBUG e.i.l.c.p.JAIUtil - scaleImageUsingSubsampleAverage(): width: 12.676056338028168%; height: 12.684319010623119%
2018-02-23T15:01:25.388232192Z 15:01:25.388 [qtp1634198-18] DEBUG e.i.l.c.p.i.JPEGImageWriter - ImageIO plugin preferences: none
2018-02-23T15:01:25.388315687Z 15:01:25.388 [qtp1634198-18] DEBUG e.i.l.c.p.i.JPEGImageWriter - Using com.sun.imageio.plugins.jpeg.JPEGImageWriter
2018-02-23T15:01:25.388627224Z 15:01:25.388 [qtp1634198-18] DEBUG e.i.l.c.p.i.JPEGImageWriter - Quality: 80; progressive: true
2018-02-23T15:01:28.975791362Z 15:01:28.975 [qtp1634198-18] DEBUG e.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream - close(): closing stream for oocihm.8_04796_719/data/sip/data/files/oocihm.8_04796_719.0003.tif_scale:!800,800,bicubic_encode:jpg_UNDEFINED_80_interlace_#000000_8_token:eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDQVAiLCJleHAiOjE1MTk0ODQ0ODEsImRlcml2YXRpdmVGaWxlcyI6Im9vY2lobS44XzA0Nzk2XzcxOS9kYXRhL3NpcC9kYXRhL2ZpbGVzL29vY2lobS44XzA0Nzk2XzcxOS4wMDAzLnRpZiIsImlhdCI6MTUxOTM5ODA4MSwibWF4RGltZW5zaW9uIjo4MDB9.LZht9S-OjRLLAv1r3bzNuDmPrNddkQzDIHIgr4-WpPo.jpg
2018-02-23T15:01:28.975860006Z 15:01:28.975 [qtp1634198-18] DEBUG e.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream - close(): deleting zero-byte file: /var/cache/cantaloupe/image/d0/cb/a0/d0cba00530761188ed2d379a2388e00a_55761a30210791ac6c37258cd303febf.jpg_qtp1634198-18.tmp
2018-02-23T15:01:28.976568712Z 15:01:28.976 [qtp1634198-18] INFO  e.i.l.c.r.ImageRepresentation - write(): Java heap space
2018-02-23T15:01:28.977117857Z 15:01:28.976 [qtp1634198-18] INFO  e.i.l.c.c.FilesystemCache - purge(OperationList): purging oocihm.8_04796_719/data/sip/data/files/oocihm.8_04796_719.0003.tif_scale:!800,800,bicubic_encode:jpg_UNDEFINED_80_interlace_#000000_8_token:eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDQVAiLCJleHAiOjE1MTk0ODQ0ODEsImRlcml2YXRpdmVGaWxlcyI6Im9vY2lobS44XzA0Nzk2XzcxOS9kYXRhL3NpcC9kYXRhL2ZpbGVzL29vY2lobS44XzA0Nzk2XzcxOS4wMDAzLnRpZiIsImlhdCI6MTUxOTM5ODA4MSwibWF4RGltZW5zaW9uIjo4MDB9.LZht9S-OjRLLAv1r3bzNuDmPrNddkQzDIHIgr4-WpPo.jpg...
2018-02-23T15:01:28.993609268Z 15:01:28.985 [qtp1634198-18] ERROR o.r.C.Server - An exception occurred writing the response entity
2018-02-23T15:01:28.993663214Z java.lang.NullPointerException: null
2018-02-23T15:01:28.993672427Z 	at edu.illinois.library.cantaloupe.processor.imageio.AbstractImageReader.readSmallestUsableSubimage(AbstractImageReader.java:551)
2018-02-23T15:01:28.993683031Z 	at edu.illinois.library.cantaloupe.processor.imageio.TIFFImageReader.readRendered(TIFFImageReader.java:201)
2018-02-23T15:01:28.993689168Z 	at edu.illinois.library.cantaloupe.processor.imageio.ImageReader.readRendered(ImageReader.java:323)
2018-02-23T15:01:28.993694595Z 	at edu.illinois.library.cantaloupe.processor.JaiProcessor.process(JaiProcessor.java:141)
2018-02-23T15:01:28.993699827Z 	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:164)
2018-02-23T15:01:28.993705036Z 	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:119)
2018-02-23T15:01:28.993710330Z 	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
2018-02-23T15:01:28.993715524Z 	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
2018-02-23T15:01:28.993720705Z 	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
2018-02-23T15:01:28.993725864Z 	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:191)
2018-02-23T15:01:28.993731245Z 	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
2018-02-23T15:01:28.993736515Z 	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
2018-02-23T15:01:28.993741804Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
2018-02-23T15:01:28.993747016Z 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
2018-02-23T15:01:28.993752599Z 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
2018-02-23T15:01:28.993757964Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
2018-02-23T15:01:28.993763021Z 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
2018-02-23T15:01:28.993768110Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2018-02-23T15:01:28.993773158Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
2018-02-23T15:01:28.993778190Z 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
2018-02-23T15:01:28.993783294Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
2018-02-23T15:01:28.993790107Z 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
2018-02-23T15:01:28.993795704Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
2018-02-23T15:01:28.993800807Z 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
2018-02-23T15:01:28.993812754Z 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
2018-02-23T15:01:28.993818538Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
2018-02-23T15:01:28.993823919Z 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
2018-02-23T15:01:28.993828994Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
2018-02-23T15:01:28.993834056Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2018-02-23T15:01:28.993838971Z 	at org.eclipse.jetty.server.Server.handle(Server.java:561)
2018-02-23T15:01:28.993843945Z 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
2018-02-23T15:01:28.993848804Z 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
2018-02-23T15:01:28.993853810Z 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
2018-02-23T15:01:28.993858799Z 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
2018-02-23T15:01:28.993863716Z 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
2018-02-23T15:01:28.993868585Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
2018-02-23T15:01:28.993873599Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
2018-02-23T15:01:28.993878550Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
2018-02-23T15:01:28.993883736Z 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
2018-02-23T15:01:28.993888898Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
2018-02-23T15:01:28.993894141Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
2018-02-23T15:01:28.993899105Z 	at java.lang.Thread.run(Thread.java:748)

```

An identical request made later works without any problem, so the problem isn't an error in the source file.

**Comment by adolski** [comment]
This line:
```
2018-02-23T15:01:28.976568712Z 15:01:28.976 [qtp1634198-18] INFO  e.i.l.c.r.ImageRepresentation - write(): Java heap space
```
suggests that your JVM heap is too small and that's why a zero-byte file is being created. Also would explain why it only happens intermittently.

A patch to log that at error level instead will be arriving shortly.

**Comment by RussellMcOrmond** [comment]
I doubled the heap from 2g to 4g, and haven't seen the problem yet.

I see some notes in the documentation about heap considerations, but not specifically any recommendations.   Is this a single heap for every thread or is a heap allocated per thread?

**Comment by adolski** [comment]
The heap is per-JVM, so all threads in the JVM share the same heap. Heap requirements vary depending on the # of concurrent or closely-spaced requests (between garbage-collection cycles), source image formats, requested image sizes, the processor being used, etc. Hard to provide recommendations other than "more is better" and "keep an eye on it"  :smile:

**Comment by RussellMcOrmond** [comment]
As always, thank you so much for your help.
