### ISSUE TITLE
Using OpenJpegProcessor on Windows - JP2 requests throw NullPointerException

### ISSUE THREAD

**Issue by filak** [medusa-project/cantaloupe#206]
Requests for JPG2000 files fail, ie. 

2018-03-01 13:21:42,188 INFO [qtp1282788025-16] e.i.l.c.r.AbstractResource [AbstractResource.java:201] doInit(): handling GET http://localhost:8182/iiif/2/test1.jp2/50,50,200,200/full/0/default.jpg
2018-03-01 13:21:42,188 DEBUG [qtp1282788025-16] e.i.l.c.r.AbstractResource [AbstractResource.java:365] Identifier requested: test1.jp2 -> decoded: test1.jp2 -> slashes substituted: test1.jp2
2018-03-01 13:21:42,188 DEBUG [qtp1282788025-16] e.i.l.c.c.InfoService [InfoService.java:101] getInfo(): retrieved info of test1.jp2 from ObjectCache
2018-03-01 13:21:42,188 DEBUG [qtp1282788025-16] e.i.l.c.o.OperationList [OperationList.java:218] applyNonEndpointMutations(): redactions are disabled; skipping.
2018-03-01 13:21:42,188 DEBUG [qtp1282788025-16] e.i.l.c.o.OperationList [OperationList.java:263] applyNonEndpointMutations(): overlays are disabled; skipping.
2018-03-01 13:21:42,189 INFO [qtp1282788025-16] e.i.l.c.r.FilesystemResolver [FilesystemResolver.java:122] Resolved test1.jp2 to c:\Decko\cantaloupe\data\test1.jp2
2018-03-01 13:21:42,190 INFO [qtp1282788025-16] e.i.l.c.p.ProcessorConnector [ProcessorConnector.java:143] FileResolver -> FileProcessor connection between FilesystemResolver and OpenJpegProcessor
2018-03-01 13:21:42,191 DEBUG [qtp1282788025-16] e.i.l.c.c.InfoService [InfoService.java:101] getInfo(): retrieved info of test1.jp2 from ObjectCache
2018-03-01 13:21:42,191 DEBUG [qtp1282788025-16] e.i.l.c.a.Authorizer [Authorizer.java:111] Delegate script is disabled; allowing.
2018-03-01 13:21:42,193 DEBUG [qtp1282788025-16] e.i.l.c.r.AbstractResource [AbstractResource.java:406] Public identifier requested: test1.jp2 -> decoded: test1.jp2 -> slashes substituted: test1.jp2 | X-IIIF-ID header: null
2018-03-01 13:21:42,193 DEBUG [qtp1282788025-16] e.i.l.c.r.AbstractResource [AbstractResource.java:178] Base URI assembled from request: http://localhost:8182
2018-03-01 13:21:42,196 INFO [qtp1282788025-16] e.i.l.c.c.HeapCache [HeapCache.java:503] newDerivativeImageOutputStream(): miss; caching test1.jp2_crop:50,50,200,200_encode:jpg_UNDEFINED_80_interlace_#000000_8.jpg
2018-03-01 13:21:42,196 DEBUG [qtp1282788025-16] e.i.l.c.r.ImageRepresentation [ImageRepresentation.java:106] Writing to the response & derivative cache simultaneously
2018-03-01 13:21:42,197 DEBUG [qtp1282788025-16] e.i.l.c.c.HeapCache [HeapCache.java:184] Closing stream for test1.jp2_crop:50,50,200,200_encode:jpg_UNDEFINED_80_interlace_#000000_8.jpg
2018-03-01 13:21:42,197 INFO [qtp1282788025-16] e.i.l.c.r.ImageRepresentation [ImageRepresentation.java:116] write(): null
2018-03-01 13:21:42,197 INFO [qtp1282788025-16] e.i.l.c.c.HeapCache [HeapCache.java:525] purge(OperationList): purging test1.jp2_crop:50,50,200,200_encode:jpg_UNDEFINED_80_interlace_#000000_8.jpg...
2018-03-01 13:21:42,198 ERROR [qtp1282788025-16] o.r.C.Server [Slf4jLogger.java:230] An exception occurred writing the response entity
java.lang.NullPointerException: null
	at edu.illinois.library.cantaloupe.processor.OpenJpegProcessor.getProcessBuilder(OpenJpegProcessor.java:515)
	at edu.illinois.library.cantaloupe.processor.OpenJpegProcessor.process(OpenJpegProcessor.java:394)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:164)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:119)

**Comment by adolski** [comment]
Hi @filak,

OpenJpegProcessor doesn't work in Windows due to limitations of the `opj_decompress` tool. It will work in version 4 with impaired performance.

**Comment by filak** [comment]
OK, I will run it in VM then.
