### ISSUE TITLE
Failure to start under jetty / JDK 9

### ISSUE THREAD

**Issue by barryspearce** [medusa-project/cantaloupe#211]
Im getting a failure to start cantaloupe. 

Environment:
4core Intel 32G RAM with Manjaro 4.14.31-1 fully up to date.
jdk9-openjdk 9.0.4.u11-1
jetty 9.4.7-1
cantaloupe 3.4.2

Jetty installation tested with the Tomcat sample application. All deploying and working correctly.

This is a fresh install of jetty/cantaloupe. The cantaloupe war was dropped into the webapps directory. The following exception was reported from jetty.

`Apr 10 10:16:59 testserver.local jetty[364]: 2018-04-10 10:16:59.393:WARN:oejw.WebAppContext:Scanner-0: Failed startup of context o.e.j.w.WebAppContext@210359fb{/Cantaloupe-3.4.2,file:///tmp/jetty-0.0.0.0-8080-Cantaloupe-3.4.2.war>
Apr 10 10:16:59 testserver.local jetty[364]: MultiException[java.lang.RuntimeException: Error scanning entry org/eclipse/jetty/alpn/java/server/JDK9ServerALPNProcessor.class from jar file:///tmp/jetty-0.0.0.0-8080-Cantaloupe-3.4.2>
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:450)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:363)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1471)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:329)
Apr 10 10:16:59 testserver.local jetty[364]:         at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
Apr 10 10:16:59 testserver.local jetty[364]:         at java.base/java.util.TimerThread.run(Timer.java:506)
Apr 10 10:16:59 testserver.local jetty[364]: Suppressed:
Apr 10 10:16:59 testserver.local jetty[364]:         |java.lang.RuntimeException: Error scanning entry org/eclipse/jetty/alpn/java/client/JDK9ClientALPNProcessor.class from jar file:///tmp/jetty-0.0.0.0-8080-Cantaloupe-3.4.2.war-_>
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:911)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:857)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at java.base/java.lang.Thread.run(Thread.java:844)
Apr 10 10:16:59 testserver.local jetty[364]:         |Caused by:
Apr 10 10:16:59 testserver.local jetty[364]:         |java.lang.IllegalArgumentException
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:979)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:960)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:907)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:857)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
Apr 10 10:16:59 testserver.local jetty[364]:         |        at java.base/java.lang.Thread.run(Thread.java:844)
Apr 10 10:16:59 testserver.local jetty[364]: Caused by:
Apr 10 10:16:59 testserver.local jetty[364]: java.lang.RuntimeException: Error scanning entry org/eclipse/jetty/alpn/java/server/JDK9ServerALPNProcessor.class from jar file:///tmp/jetty-0.0.0.0-8080-Cantaloupe-3.4.2.war-_Cantaloup>
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:911)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:857)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
Apr 10 10:16:59 testserver.local jetty[364]:         at java.base/java.lang.Thread.run(Thread.java:844)
Apr 10 10:16:59 testserver.local jetty[364]: Caused by:
Apr 10 10:16:59 testserver.local jetty[364]: java.lang.IllegalArgumentException
Apr 10 10:16:59 testserver.local jetty[364]:         at org.objectweb.asm.ClassReader.<init>(Unknown Source)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:979)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:960)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:907)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:857)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
Apr 10 10:16:59 testserver.local jetty[364]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
Apr 10 10:16:59 testserver.local jetty[364]:         at java.base/java.lang.Thread.run(Thread.java:844)`

Any ideas how to resolve?

**Comment by adolski** [comment]
Hi @barryspearce,

I just tried it and got the same error. But the error is gone when I update to Jetty 9.4.9.v20180320.

**Comment by barryspearce** [comment]
Ah. This may well be related to some of the work they were doing then regarding supporting multiple java versions.
Ill upgrade and try again. Thx.
