### ISSUE TITLE
Errors delivering images after upgrading to Cantaloupe 3.4.3

### ISSUE THREAD

**Issue by cbeer** [medusa-project/cantaloupe#225]
Hi,

We recently updated our Cantaloupe server from a 3.4 snapshot (probably from somewhere around 8c90599d1ad42a3cb5a69803af4efe3e645325bd) to 3.4.3. After doing so, things look fine for ~5 minutes, and then Cantaloupe starts throwing errors and delivering 0-byte images for any new requests.

It looks like once a Tomcat thread gets the particular error, any future requests that hit that thread will error out.

Here is a sample failing request from our tomcat log (with cantaloupe set to TRACE level logging):

```
08:10:25.325 [ajp-apr-8009-exec-10] ^[[34mINFO ^[[0;39m ^[[36me.i.l.c.r.AbstractResource^[[0;39m - doInit(): handling GET http://imageserver-prod.stanford.edu/iiif/2/sx%2F200%2Fwv%2F7668%2F044_125_TC_46.jp2/full/pct:6.25/0/default.jpg
08:10:25.325 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.r.AbstractResource^[[0;39m - Identifier requested: sx%2F200%2Fwv%2F7668%2F044_125_TC_46.jp2 -> decoded: sx/200/wv/7668/044_125_TC_46.jp2 -> slashes substituted: sx/200/wv/7668/044_125_TC_46.jp2
08:10:25.325 [ajp-apr-8009-exec-10] ^[[34mINFO ^[[0;39m ^[[36me.i.l.c.c.FilesystemCache^[[0;39m - getImageInfo(): hit: /image-cache/cantaloupe-3.4.3/info/eb/b2/1d/ebb21d9fbb4fcad9e3f45fbec1dc78f0.json
08:10:25.328 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.c.InfoService^[[0;39m - getInfo(): retrieved info of sx/200/wv/7668/044_125_TC_46.jp2 from FilesystemCache in 3 msec
08:10:25.328 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.c.InfoService^[[0;39m - putInObjectCache(): ObjectCache is disabled; doing nothing
08:10:25.328 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.o.OperationList^[[0;39m - applyNonEndpointMutations(): redactions are disabled; skipping.
08:10:25.328 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.o.OperationList^[[0;39m - applyNonEndpointMutations(): overlays are disabled; skipping.
08:10:25.329 [ajp-apr-8009-exec-10] ^[[34mINFO ^[[0;39m ^[[36me.i.l.c.r.FilesystemResolver^[[0;39m - Resolved sx/200/wv/7668/044_125_TC_46.jp2 to /stacks/sx/200/wv/7668/044_125_TC_46.jp2
08:10:25.329 [ajp-apr-8009-exec-10] ^[[34mINFO ^[[0;39m ^[[36me.i.l.c.p.ProcessorConnector^[[0;39m - FileResolver -> FileProcessor connection between FilesystemResolver and KakaduProcessor
08:10:25.329 [ajp-apr-8009-exec-10] ^[[34mINFO ^[[0;39m ^[[36me.i.l.c.c.FilesystemCache^[[0;39m - getImageInfo(): hit: /image-cache/cantaloupe-3.4.3/info/eb/b2/1d/ebb21d9fbb4fcad9e3f45fbec1dc78f0.json
08:10:25.331 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.c.InfoService^[[0;39m - getInfo(): retrieved info of sx/200/wv/7668/044_125_TC_46.jp2 from FilesystemCache in 2 msec
08:10:25.331 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.c.InfoService^[[0;39m - putInObjectCache(): ObjectCache is disabled; doing nothing
08:10:25.331 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.a.Authorizer^[[0;39m - Delegate script is disabled; allowing.
08:10:25.332 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.r.AbstractResource^[[0;39m - Public identifier requested: sx%2F200%2Fwv%2F7668%2F044_125_TC_46.jp2 | X-IIIF-ID header: null
08:10:25.332 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.r.AbstractResource^[[0;39m - X-Forwarded headers: Proto: HTTP; Host: null; Port: null; Path:
08:10:25.332 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.r.AbstractResource^[[0;39m - Base URI assembled: http://imageserver-prod.stanford.edu
08:10:25.333 [ajp-apr-8009-exec-10] ^[[34mINFO ^[[0;39m ^[[36me.i.l.c.c.FilesystemCache^[[0;39m - newOutputStream(): miss; caching sx/200/wv/7668/044_125_TC_46.jp2_scale:6.25%,bicubic_encode:jpg_UNDEFINED_80_interlace_#000000_8.jpg
08:10:25.334 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.r.ImageRepresentation^[[0;39m - Writing to the response & derivative cache simultaneously
08:10:25.335 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.KakaduProcessor^[[0;39m - Invoking kdu_expand -quiet -resilient -no_alpha -i /stacks/sx/200/wv/7668/044_125_TC_46.jp2 -reduce 4 -o /var/cache/tomcat/temp/cantaloupe-KakaduProcessor-68108fe0-5b57-4c8f-a0ea-7611ad8aaeb3.tif
08:10:25.337 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.i.TIFFImageReader^[[0;39m - ImageIO plugin preferences: it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader, com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader
08:10:25.337 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.i.TIFFImageReader^[[0;39m - Using it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader
08:10:25.337 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.i.TIFFImageReader^[[0;39m - Ignoring metadata? true
08:10:25.475 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream^[[0;39m - close(): closing stream for sx/200/wv/7668/044_125_TC_46.jp2_scale:6.25%,bicubic_encode:jpg_UNDEFINED_80_interlace_#000000_8.jpg
08:10:25.475 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream^[[0;39m - close(): deleting zero-byte file: /image-cache/cantaloupe-3.4.3/image/eb/b2/1d/ebb21d9fbb4fcad9e3f45fbec1dc78f0_9fde6c4126fffc770869a1f40a9257b5.jpg_ajp-apr-8009-exec-10.tmp
08:10:25.477 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.r.ImageRepresentation^[[0;39m - write(): I/O error reading header!
08:10:25.477 [ajp-apr-8009-exec-10] ^[[34mINFO ^[[0;39m ^[[36me.i.l.c.c.FilesystemCache^[[0;39m - purge(OperationList): purging sx/200/wv/7668/044_125_TC_46.jp2_scale:6.25%,bicubic_encode:jpg_UNDEFINED_80_interlace_#000000_8.jpg...
08:10:25.478 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.KakaduProcessor^[[0;39m - Invoking kdu_expand -quiet -resilient -no_alpha -i /stacks/sx/200/wv/7668/044_125_TC_46.jp2 -reduce 4 -o /var/cache/tomcat/temp/cantaloupe-KakaduProcessor-68108fe0-5b57-4c8f-a0ea-7611ad8aaeb3.tif
08:10:25.480 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.i.TIFFImageReader^[[0;39m - ImageIO plugin preferences: it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader, com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader
08:10:25.480 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.i.TIFFImageReader^[[0;39m - Using it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader
08:10:25.480 [ajp-apr-8009-exec-10] ^[[39mDEBUG^[[0;39m ^[[36me.i.l.c.p.i.TIFFImageReader^[[0;39m - Ignoring metadata? true
08:10:25.632 [ajp-apr-8009-exec-10] ^[[1;31mERROR^[[0;39m ^[[36me.i.l.c.r.ImageRepresentation^[[0;39m - Failed to read from the derivative cache: I/O error reading header!
java.io.IOException: I/O error reading header!
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:181)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:141)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:191)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: edu.illinois.library.cantaloupe.processor.ProcessorException: I/O error reading header!
	at edu.illinois.library.cantaloupe.processor.KakaduProcessor.process(KakaduProcessor.java:401)
	at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:175)
	... 28 common frames omitted
Caused by: javax.imageio.IIOException: I/O error reading header!
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.readHeader(TIFFImageReader.java:505)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.locateImage(TIFFImageReader.java:643)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.seekToImage(TIFFImageReader.java:773)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.seekToImage(TIFFImageReader.java:760)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.prepareRead(TIFFImageReader.java:1530)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1724)
	at javax.imageio.ImageReader.read(ImageReader.java:939)
	at edu.illinois.library.cantaloupe.processor.imageio.AbstractImageReader.read(AbstractImageReader.java:289)
	at edu.illinois.library.cantaloupe.processor.imageio.ImageReader.read(ImageReader.java:199)
	at edu.illinois.library.cantaloupe.processor.KakaduProcessor.process(KakaduProcessor.java:371)
	... 29 common frames omitted
Caused by: java.io.EOFException: null
	at javax.imageio.stream.ImageInputStreamImpl.readShort(ImageInputStreamImpl.java:229)
	at javax.imageio.stream.ImageInputStreamImpl.readUnsignedShort(ImageInputStreamImpl.java:242)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.readHeader(TIFFImageReader.java:451)
	... 38 common frames omitted
```

Any ideas how to start debugging this problem?

Thanks,
Chris

**Comment by adolski** [comment]
KakaduProcessor is invoking `kdu_expand` on an on-disk JP2 file, which transcodes it to TIFF and streams it back to the application in a Rube Goldbergesque way involving a symlink to `/dev/stdout`:

https://github.com/medusa-project/cantaloupe/blob/aa9d2920863eeed7e216473cac6d50288c927638/src/main/java/edu/illinois/library/cantaloupe/processor/KakaduProcessor.java#L72-L80

The symlink is created during initialization and its pathname is the `-o` argument of this command:

```
09:11:41.307 [http-apr-8080-exec-5] DEBUG e.i.l.c.p.KakaduProcessor - Invoking kdu_expand -quiet -resilient -no_alpha -i /stacks/pf/437/st/2633/pf437st2633_00_0265.jp2 -region {0.49242,0.76503},{0.49242,0.76503} -reduce 2 -o /var/cache/tomcat/temp/cantaloupe-KakaduProcessor-68108fe0-5b57-4c8f-a0ea-7611ad8aaeb3.tif
```

I don't know how `/var/cache/tomcat/temp` is managed, but I wonder if Tomcat is deleting it, after about ~5 minutes? That'd be my guess. If confirmed, you might want to use the `temp_pathname` key to choose a different temp dir.

**Comment by cbeer** [comment]
Ah ha, thank you! This is all coming back to me now, it's related to #159. Because we were on a snapshot that predated that fix, we had a workaround that was "helpfully" cleaning up `/var/cache/tomcat/temp`. I bet that'll fix it.
