### ISSUE TITLE
Too many http connections by HttpSource with Cantaloupe 4.0

### ISSUE THREAD

**Issue by giancarlobi** [medusa-project/cantaloupe#229]
When I switch from 3.4.1 to 4.0 I see Cantaloupe hangs for a while when loaded and there are a lot of tcp connections to source image backend but with 3.4.1 all works good and tcp connections are very limited to a couple.
In addition with 4.0 I have to set HttpSource.request_timeout very high (300 s) to avoid cantaloupe stops working but with 3.4.1 and default 10s all is working properly.
Both configurations (4.0 and 3.4.1) has been checked with the same machine, frontends and backends.

**Comment by giancarlobi** [comment]
More, also with 3.4.3 is working well.
TCP connections with 3.4.x are opened and closed fast but with 4.0 connections are not well closed so we have to wait timeout before open more.

**Comment by adolski** [comment]
Thanks for reporting this, @giancarlobi . I can reproduce it and will commit a fix shortly.

**Comment by giancarlobi** [comment]
Great!! many thanks @adolski

**Comment by adolski** [comment]
Fix now available on `release/4.0` branch.

**Comment by giancarlobi** [comment]
It works like a charm, thanks !!!

**Comment by giancarlobi** [comment]
@adolski , ehm ... After some hours working the server hangs with open connections "time_wait" to back-end source tiles very similar before fix. It doesn't depend on back-end image source. I have to restart cantaloupe to make it working again.
Nothing interesting into error.log.
I revert to 3.4.3 as the server is in production and it works fine. Maybe next week I can make some more checks.

**Comment by giancarlobi** [comment]
@adolski I upgraded production server to 4.0.1-SNAPSHOT, setting a daily server restart, all good for a while but yesterday it hanged again. 
I noticed in syslog the message below repeated a lot of time, finally the server hangs with a lot of connection appended between front-end and cantaloupe server.

> Aug 16 06:34:47 digiimage java[29080]: 2018-08-16 06:34:47.872:WARN:oeji.SelectorManager:HttpClient@279e2242-886: Exception while notifying connection HttpConnectionOverHTTP@1
f6616e3(l:/123.123.123.55:43260 <-> r:/123.123.123.48:8080,closed=false)=>HttpChannelOverHTTP@727aca1d(exchange=null)[send=HttpSenderOverHTTP@4eada267(req=QUEUED,snd=IDLE,failur
e=null)[HttpGenerator@628e7394{s=START}],recv=HttpReceiverOverHTTP@4d70b028(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]<-SocketChannelEndPoint@697ea1b9{/123.123.123.48
:8080<->/123.123.123.55:43260,OPEN,fill=FI,flush=-,to=11/0}{io=1/1,kio=1,kro=8}->HttpConnectionOverHTTP@1f6616e3(l:/123.123.123.55:43260 <-> r:/123.123.123.48:8080,closed=false)=
>HttpChannelOverHTTP@727aca1d(exchange=null)[send=HttpSenderOverHTTP@4eada267(req=QUEUED,snd=IDLE,failure=null)[HttpGenerator@628e7394{s=START}],recv=HttpReceiverOverHTTP@4d70
b028(rsp=IDLE,failure=null)[HttpParser{s=START,0 of -1}]]
Aug 16 06:34:47 digiimage java[29080]: java.lang.NullPointerException
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.util.AbstractAuthentication.matchesURI(AbstractAuthentication.java:64)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.HttpAuthenticationStore.findAuthenticationResult(HttpAuthenticationStore.java:89)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.HttpConnection.applyAuthentication(HttpConnection.java:176)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.HttpConnection.normalizeRequest(HttpConnection.java:156)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:245)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:122)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:347)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:305)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:295)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.HttpDestination.succeeded(HttpDestination.java:229)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.AbstractConnectionPool.proceed(AbstractConnectionPool.java:154)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:132)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.AbstractConnectionPool$1.succeeded(AbstractConnectionPool.java:124)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.util.Promise$Wrapper.succeeded(Promise.java:130)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onOpen(HttpConnectionOverHTTP.java:130)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.io.SelectorManager.connectionOpened(SelectorManager.java:320)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:227)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.io.ManagedSelector.access$1500(ManagedSelector.java:60)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:825)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
Aug 16 06:34:47 digiimage java[29080]: #011at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
Aug 16 06:34:47 digiimage java[29080]: #011at java.lang.Thread.run(Thread.java:748)
Aug 16 06:34:47 digiimage java[29080]: 2018-08-16 06:34:47.879:WARN:oeji.ManagedSelector:HttpClient@279e2242-886: java.lang.NullPointerException

**Comment by adolski** [comment]
Hi @giancarlobi,

I'm not able to reproduce this on the `release/4.0` branch (4.0.1-SNAPSHOT). While running a script that uses curl to request images in a loop, netstat does not report anything interesting -- just a steady small number of connections and none that enter `CLOSE_WAIT` state.

My config file is using all default settings, except
```
source.static = HttpSource
HttpSource.BasicLookupStrategy.url_prefix = ...
```
I request source JPEGs handled by Java2dProcessor. Let me know if I should try something else.

**Comment by giancarlobi** [comment]
@adolski thanks to check this.
I use backend (fedora repo 3.8.1) for JPG2000 source handled by KakaduNativeProcessor, provided to front-end Islandora. I'm running on Ubuntu 16.04 and Cantaloupe is the only one service.
Here my settings diff vs default sample proprieties file:
< temp_pathname = /srv/tmp
< http.host = 123.123.123.55
< endpoint.iiif.min_tile_size = 1024
< endpoint.admin.enabled = true
< endpoint.admin.username = admin
< endpoint.admin.secret = password
< endpoint.api.enabled = true
< endpoint.api.username = admin
< endpoint.api.secret = password
< source.static = HttpSource
< FilesystemSource.BasicLookupStrategy.path_prefix = /tmp/
< HttpSource.trust_all_certs = true
< HttpSource.request_timeout = 10
< HttpSource.BasicLookupStrategy.url_prefix =
< HttpSource.BasicLookupStrategy.auth.basic.username = username
< HttpSource.BasicLookupStrategy.auth.basic.secret = password
< processor.stream_retrieval_strategy = CacheStrategy
< processor.background_color = black
< ImageMagickProcessor.path_to_binaries = /usr/local/bin
< cache.server.source.ttl_seconds = 86400
< cache.server.derivative.enabled = true
< cache.server.derivative = FilesystemCache
< cache.server.derivative.ttl_seconds = 86400
< cache.server.worker.enabled = true
< cache.server.worker.interval = 43200
< FilesystemCache.pathname = /srv/cache
< overlays.BasicStrategy.string = Copyright \u00A9\u00EF\u00B8\u008F My Great Organization\nAll rights reserved.
< log.application.level = warn
< log.application.ConsoleAppender.enabled = false
< log.application.FileAppender.pathname = /srv/log/application.log
< log.application.RollingFileAppender.enabled = true
< log.application.RollingFileAppender.pathname = /srv/log/application.log
< log.application.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /srv/log/application-%d{yyyy-MM-dd}.log
< log.error.FileAppender.enabled = true
< log.error.FileAppender.pathname = /srv/log/error.log
< log.error.RollingFileAppender.pathname = /srv/log/error.log
< log.error.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /srv/log/error-%d{yyyy-MM-dd}.log
< log.access.FileAppender.pathname = /srv/log/access.log
< log.access.RollingFileAppender.pathname = /srv/log/access.log
< log.access.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /srv/log/access-%d{yyyy-MM-dd}.log

Anyway many thanks!

**Comment by giancarlobi** [comment]
@adolski this is the graph of network TCP stack around server hang, green TCP established , grey TCP time-wait, if can help. Server hangs near 10:30 then I restarted after 11:00 and it start working again.
![image](https://user-images.githubusercontent.com/4232178/44222045-a670d400-a183-11e8-903b-b7dd18dc3668.png)

**Comment by giancarlobi** [comment]
@adolski, more details:
- the graph is relative to backend-cantaloupe connections
- when the server hangs, cached images are provided to front-end while hangs on new no cached images

**Comment by giancarlobi** [comment]
@adolski when cantaloupe stopped to retrive remote images, a couples of this errors were logged:

2018-08-16 10:28:21,147 ERROR [qtp1729199940-1647] o.r.C.RestletApplication [Slf4jLogger.java:230] Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
        at org.restlet.resource.ServerResource.get(ServerResource.java:723)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
        at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)
        at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
        at org.restlet.resource.ServerResource.handle(ServerResource.java:1020)
        at org.restlet.resource.Finder.handle(Finder.java:236)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
        at org.restlet.Application.handle(Application.java:385)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.Component.handle(Component.java:408)
        at org.restlet.Server.handle(Server.java:507)
        at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:856)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null

**Comment by adolski** [comment]
Hi @giancarlobi,

I think whatever is happening with `TIME_WAIT` connections is different from the original issue here.

When I use a configuration similar to yours with 4.0.1-SNAPSHOT: 
```
processor.jp2 = KakaduNativeProcessor
processor.stream_retrieval_strategy = CacheStrategy
```
And run my request-images-in-a-loop script against the server, running on macOS, I can see the number of `TIME_WAIT` connections increase up to a little over 100, and then remain steady there. I don't see any `CLOSE_WAIT`s which would indicate a programming error. But `TIME_WAIT` is a normal stage in the TCP lifecycle and these connections aren't concerning, I wouldn't think. (?)

The graph you posted is interesting. Usually a leak on a graph would look like a steady incline, but this doesn't show that.

Have you tried reducing the `TIME_WAIT` interval on your server? You would probably know more about this than I would, but, just an idea.

I can't make out much from the stack traces you posted, except the last one which looks like some exception is being caught that has a null message and the NullPointerException from that is obscuring the actual error, so I've patched that, above.

**Comment by giancarlobi** [comment]
Just few minutes ago server hang again, stop answering for no cached image, and I found this in log:

2018-08-17 23:17:15,206 ERROR [qtp1729199940-94] o.r.C.RestletApplication [Slf4jLogger.java:230] Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
...
**Caused by: java.lang.IllegalArgumentException: Malformed URI:** http%3A%2F%2F150.145.48.48%3A8080%2Ffedora%2Fobjects%2Flibrib%3A88487%2Fdatastreams%2FJP2%2Fcontent
        at edu.illinois.library.cantaloupe.source.HttpSource.fetchRangedGETResponse(HttpSource.java:422)
        at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:236)
        at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:120)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
        ... 68 common frames omitted

but URI is not malformed, I tested it.

![image](https://user-images.githubusercontent.com/4232178/44291659-15335780-a280-11e8-9521-868d27fdbbce.png)
A lot of close-wait socket, I think due to no answer to image no cached.
The graph now includes connection to frontend and backend.
After restart all goes ok.

Thanks really a lot @adolski to spend you time about this.

**Comment by giancarlobi** [comment]
@adolski thanks again, I know that this maybe a problem of my frontend/backend and not cantaloupe, I really check every things, I'd be happy to solve this issue, so again thanks for your time.

**Comment by giancarlobi** [comment]
@adolski I think it's better open a new issue: https://github.com/medusa-project/cantaloupe/issues/232

**Comment by giancarlobi** [comment]
@adolski I think this issue can be closed from my point of view
