### ISSUE TITLE
JP2 source contains a file type box whose compatibility list does not include JP2

### ISSUE THREAD

**Issue by deutsches-museum-digital** [medusa-project/cantaloupe#230]
[5678-5678_0023.jp2.zip](https://github.com/medusa-project/cantaloupe/files/2279449/5678-5678_0023.jp2.zip)

At the moment I am evaluating Cantaloupe as a means for graphics delivery in our project "Deutsches Museum Digital", where digitized exhibits, library items and archivalia from our museum are being published on the Net. As the base format for IIIF delivery of the graphics files connected with the digitized items we chose Jpeg2000, which we deem best practice. With Cantaloupe, everything seems to work very well and so far we are quite pleased.

The only issue we encountered is with our digitized library items. There, any attempt to get a picture like so (or with any other IIIF compatible request) yields a 500:

```
http://localhost:8182/iiif/2/5678-5678_0023.jp2/full/full/0/default.jpg
```

The relevant output of Cantaloupe (running on Debian 9) contains these lines:

```
20:58:11.742 [qtp959447386-29] DEBUG e.i.l.c.s.DelegateProxy - Entered filesystemsource_pathname
20:58:11.743 [qtp959447386-29] DEBUG e.i.l.c.s.DelegateProxy - File path to return:
20:58:11.743 [qtp959447386-29] DEBUG e.i.l.c.s.DelegateProxy - /home/sigi/pix/dmdpix/img/obj/5678-5678/5678-5678_0023.jp2
20:58:11.743 [qtp959447386-29] DEBUG e.i.l.c.s.DelegateProxy - invokeUncached(): filesystemsource_pathname returned /home/sigi/pix/dmdpix/img/obj/5678-5678/5678-5678_0023.jp2 for args: (none) in 1 msec
20:58:11.743 [qtp959447386-29] INFO  e.i.l.c.s.FilesystemSource - Resolved 5678-5678_0023.jp2 to /home/sigi/pix/dmdpix/img/obj/5678-5678/5678-5678_0023.jp2
20:58:11.743 [qtp959447386-29] INFO  e.i.l.c.p.ProcessorConnector - FileSource -> FileProcessor connection between FilesystemSource and KakaduNativeProcessor
20:58:11.744 [qtp959447386-29] ERROR e.i.l.c.p.KakaduNativeProcessor - Error in Kakadu File Format Support:
JP2 source contains a file type box whose compatibility list does not include
JP2.

20:58:11.744 [qtp959447386-29] ERROR o.r.C.RestletApplication - Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
	at org.restlet.resource.ServerResource.get(ServerResource.java:723)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1020)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:856)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: null (code: 6b647543)
	at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.readImageInfo(KakaduNativeProcessor.java:831)
	at edu.illinois.library.cantaloupe.cache.InfoService.readInfo(InfoService.java:199)
	at edu.illinois.library.cantaloupe.cache.InfoService.getOrReadInfo(InfoService.java:135)
	at edu.illinois.library.cantaloupe.cache.CacheFacade.getOrReadInfo(CacheFacade.java:67)
	at edu.illinois.library.cantaloupe.resource.AbstractResource.getOrReadInfo(AbstractResource.java:443)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGet(InformationResource.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
	... 64 common frames omitted
Caused by: kdu_jni.KduException: null
	at kdu_jni.Jp2_source.Read_header(Native Method)
	at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.readImageInfo(KakaduNativeProcessor.java:783)
	... 74 common frames omitted
```

I got the suspicion that the lines containing "Error in Kakadu File Format Support: JP2 source contains a file type box whose compatibility list does not include JP2." are most relevant. The Jpeg2000 files in question derive from TIFF originals which were produced by a commercial Zeutschel book scanner. I convert them using a command like the following:

```
kdu_compress -i 5678-5678_0023.tif -o 5678-5678_0023.jp2 -rate 2.5  Clayers=1 Clevels=7 "Cprecincts={256,256}" "Corder=RPCL" "Cblk={64,64}" Cuse_sop=yes
```

I use the same syntax for converting TIFF originals coming from cameras and scanners of other types, and there everything works flawlessly with Cantaloupe/Kakadu. So I believe that the issue has got to do something with the TIFF originals.

Do you have any thoughts or experiences concerning this? I am attaching a typical book scan page in Jpeg2000 format for reference. If any other information would be helpful, please tell me and I will be glad to provide it.

Thank you in advance for your replies!

Siegfried

**Comment by adolski** [comment]
Hi Siegfried,

That message is emitted from the Kakadu library. KakaduNativeProcessor uses the `kdu_region_decompressor` class to do its work; this is higher-level API that is easier to work with than the lower-level structures offered by Kakadu, but it's a little bit strict about file validity, and there are no "switches" in the API to make it more lenient.

Here is how [jpylyzer](http://jpylyzer.openpreservation.org) sees your file's file type box (`cL` = "compatibility list"):

        <fileTypeBox>
            <br>jpx </br>
            <minV>0</minV>
            <cL>jpx </cL>
            <cL>jpxb</cL>
        </fileTypeBox>

About the compatibility list, the JP2 standard document (ISO/IEC 15444-1:2004) says in sec. 1.5.2:

> This field is encoded as a four-byte string of ISO/IEC 646 characters. A file that conforms to this Recommendation | International Standard shall have at least one CLi field in the File Type box, and shall contain the value 'jp2\040' in one of the CLi fields in the File Type box, and all conforming readers shall properly interpret all files with 'jp2\040' in one of the CLi fields

So we are missing a `jp2\040` here.

FWIW, when I compress a random TIFF file using your kdu_compress command (v7.10.4), here is how jpylyzer sees the file type box of the resulting file:

        <fileTypeBox>
            <br>jp2 </br>
            <minV>0</minV>
            <cL>jp2 </cL>
        </fileTypeBox>

Success, and KakaduNativeProcessor is able to read the resulting image. But, like you said, this doesn't happen with all TIFF files, only ones from a Zeutschel scanner, which is interesting. I wonder if changing your kdu_compress version, or the arguments you pass to it, could change the way the compatibility list is generated?

**Comment by adolski** [comment]
On the `develop` branch, KakaduNativeProcessor can now read JP2-compatible JPX files, including this one.
