### ISSUE TITLE
Server stops to retrieve remote http source files

### ISSUE THREAD

**Issue by giancarlobi** [medusa-project/cantaloupe#232]
When the issue happens Cantaloupe (4.0.1) no more retrieves remote http source files and only return local cached images.
When issue starts a first error is logged reporting malformed URI but it is not malformed and it's normally works:

`2018-08-19 11:18:12,838 ERROR [qtp1729199940-1543] o.r.C.RestletApplication [Slf4jLogger.java:230] Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
	at org.restlet.resource.ServerResource.get(ServerResource.java:723)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
...

Caused by: java.lang.IllegalArgumentException: Malformed URI: http%3A%2F%2F123.123.123.48%3A8080%2Ffedora%2Fobjects%2Flibrib%3A88487%2Fdatastreams%2FJP2%2Fcontent
	at edu.illinois.library.cantaloupe.source.HttpSource.fetchRangedGETResponse(HttpSource.java:422)
	at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:236)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:120)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
	... 64 common frames omitted
`

After this entry, logged multiple entries like this one, i think due to remote http source not retrieved:

`
2018-08-19 11:23:58,370 ERROR [qtp1729199940-1525] o.r.C.RestletApplication [Slf4jLogger.java:230] Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
	at org.restlet.resource.ServerResource.get(ServerResource.java:723)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
...

Caused by: java.lang.NullPointerException: null
	at org.eclipse.jetty.client.util.AbstractAuthentication.matchesURI(AbstractAuthentication.java:64)
	at org.eclipse.jetty.client.HttpAuthenticationStore.findAuthenticationResult(HttpAuthenticationStore.java:89)
	at org.eclipse.jetty.client.HttpConnection.applyAuthentication(HttpConnection.java:176)
	at org.eclipse.jetty.client.HttpConnection.normalizeRequest(HttpConnection.java:156)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP$Delegate.send(HttpConnectionOverHTTP.java:245)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.send(HttpConnectionOverHTTP.java:122)
	at org.eclipse.jetty.client.http.HttpDestinationOverHTTP.send(HttpDestinationOverHTTP.java:38)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:347)
	at org.eclipse.jetty.client.HttpDestination.process(HttpDestination.java:305)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:295)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:270)
	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:247)
	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:573)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:727)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:680)
	at edu.illinois.library.cantaloupe.source.HttpSource.fetchRangedGETResponse(HttpSource.java:417)
	at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:236)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:120)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
	... 68 common frames omitted
`

Ubuntu 16.04, Cantaloupe 4.0.1, JPeg2000 files and front-end Islandora + backend Fedora repository.

**Comment by giancarlobi** [comment]
Here my settings diff vs default sample proprieties file:

< temp_pathname = /srv/tmp
< http.host = 123.123.123.55
< endpoint.iiif.min_tile_size = 1024
< endpoint.admin.enabled = true
< endpoint.admin.username = admin
< endpoint.admin.secret = password
< endpoint.api.enabled = true
< endpoint.api.username = admin
< endpoint.api.secret = password
< source.static = HttpSource
< FilesystemSource.BasicLookupStrategy.path_prefix = /tmp/
< HttpSource.trust_all_certs = true
< HttpSource.request_timeout = 10
< HttpSource.BasicLookupStrategy.url_prefix =
< HttpSource.BasicLookupStrategy.auth.basic.username = username
< HttpSource.BasicLookupStrategy.auth.basic.secret = password
< processor.stream_retrieval_strategy = CacheStrategy
< processor.background_color = black
< ImageMagickProcessor.path_to_binaries = /usr/local/bin
< cache.server.source.ttl_seconds = 86400
< cache.server.derivative.enabled = true
< cache.server.derivative = FilesystemCache
< cache.server.derivative.ttl_seconds = 86400
< cache.server.worker.enabled = true
< cache.server.worker.interval = 43200
< FilesystemCache.pathname = /srv/cache
< overlays.BasicStrategy.string = Copyright \u00A9\u00EF\u00B8\u008F My Great Organization\nAll rights reserved.
< log.application.level = warn
< log.application.ConsoleAppender.enabled = false
< log.application.FileAppender.pathname = /srv/log/application.log
< log.application.RollingFileAppender.enabled = true
< log.application.RollingFileAppender.pathname = /srv/log/application.log
< log.application.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /srv/log/application-%d{yyyy-MM-dd}.log
< log.error.FileAppender.enabled = true
< log.error.FileAppender.pathname = /srv/log/error.log
< log.error.RollingFileAppender.pathname = /srv/log/error.log
< log.error.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /srv/log/error-%d{yyyy-MM-dd}.log
< log.access.FileAppender.pathname = /srv/log/access.log
< log.access.RollingFileAppender.pathname = /srv/log/access.log
< log.access.RollingFileAppender.TimeBasedRollingPolicy.filename_pattern = /srv/log/access-%d{yyyy-MM-dd}.log

**Comment by giancarlobi** [comment]
Hi @adolski,
about graph I'm using Zabbix to collect data from my servers. For Cantaloupe I activated a script to collect socket/TCP, you can find it here https://github.com/omni-lchen/zabbix-tcp.

About issue, I'll compile with your last patch this night and I keep you informed about that.

Last 24 hours no issue, this is the graph:
![image](https://user-images.githubusercontent.com/4232178/44357377-25cb1400-a4b2-11e8-89ac-22552a4a48d9.png)
as you can see, I set a trigger if close-wait # go upper 20.

**Comment by giancarlobi** [comment]
@adolski cantaloupe 4.0.2-SNAPSHOT was running for 6 days without any issue then yesterday in few minutes it happened again twice: @ 23:19 , then I restarted service (23:46), and @ 23:58, then I restarted service (00:57).
The graph:
![image](https://user-images.githubusercontent.com/4232178/44647406-462d2e00-a9de-11e8-80a9-05dc247bc578.png)

One hour before first leak this line was logged, I don't know if related to issue:

`2018-08-26 22:24:29,247 ERROR [qtp1729199940-17871] o.r.C.Server [Slf4jLogger.java:230] An exception occurred writing the response entity
java.lang.IllegalArgumentException: Rendered region is not entirely within the full image on the canvas. This is probably a bug. (Region: 0,0/2147483647x2147483647; image: 0,0/1x1)
        at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.readRegion(KakaduNativeProcessor.java:512)
        at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.process(KakaduNativeProcessor.java:366)

...
`

This is the first line was logged when both leaks appeared:

`2018-08-26 23:19:30,751 ERROR [qtp1729199940-17979] o.r.C.RestletApplication [Slf4jLogger.java:230] Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
        at org.restlet.resource.ServerResource.get(ServerResource.java:723)

...

Caused by: java.lang.IllegalArgumentException: Invalid URI host: null (authority: null)
        at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:503)
        at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:488)

...`

After line above, lines as the one below were logged several times:

`2018-08-26 23:19:30,933 ERROR [qtp1729199940-17813] o.r.C.RestletApplication [Slf4jLogger.java:230] Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
        at org.restlet.resource.ServerResource.get(ServerResource.java:723)

...

Caused by: java.lang.NullPointerException: null
        at org.eclipse.jetty.client.util.AbstractAuthentication.matchesURI(AbstractAuthentication.java:64)
        at org.eclipse.jetty.client.HttpAuthenticationStore.findAuthenticationResult(HttpAuthenticationStore.java:89)
        at org.eclipse.jetty.client.HttpConnection.applyAuthentication(HttpConnection.java:176)
...`

**Comment by adolski** [comment]
Thanks @giancarlobi . Lots of interesting info.

1. I don't know what to make of that graph... why no `CLOSE_WAIT`s for so long and then a sudden increase?
2. The IllegalArgumentException in KakaduNativeProcessor is probably not related. Not sure what's going on there, would need to see the request URI and source image dimensions.

    (I noticed earlier that your log level is set to `warn`. If you are able to bump it up to `info`, then request URIs would get logged as well. This would make it possible to associate errors with the request URIs that caused them using the thread ID, which is the 2nd part of the log message, for example:

    15:46:59.000 [*qtp2031588185-35*] INFO e.i.l.c.r.AbstractResource - doInit(): handling GET http://....
    15:46:59.001 [*qtp2031588185-35*] ERROR ....

3. I can reproduce the "IllegalArgumentException: Invalid URI host" by doing the following:

    ```
    HttpSource.lookup_strategy = BasicLookupStrategy
    HttpSource.BasicLookupStrategy.url_prefix =
    HttpSource.BasicLookupStrategy.url_suffix =
    ```

    Then requesting an identifier like: `http%2F%2Flocalhost%2F%2Fimage.jpg` (note missing `%2A` after `http` -- it's malformed)

    Is it possible that you are requesting some malformed URIs?

    I think this is probably not related to any leaks, either, though.

**Comment by giancarlobi** [comment]
@adolski thanks, I try some answers:
1. When CLOSE_WAIT start increasing I noted that front-end opens connection to cantaloupe to request tile and, if image is not cached, cantaloupe doesn't open connection to back-end but neither close connection with front-end. I checked this and I verified that if front-end request a tile of image cached cantaloupe works right.
2. I'll be very busy at work next two weeks so probably I'll increase log level later.
3. I'm near secure that URIs are not malformed and I'll confirm this with log level INFO set.

**Comment by giancarlobi** [comment]
@adolski I changed log level to INFO so if something happens I can relate better.

**Comment by giancarlobi** [comment]
@adolski, after 15 good days it happened again this morning 3 times. Attached application log, I don't see anything interesting but maybe useful for you.
The graph to relate time with log:

![image](https://user-images.githubusercontent.com/4232178/45416567-7f24fe00-b680-11e8-85f1-376dbbd0b254.png)

Take into account that I scheduled a script every 15 minutes to restart service if close-wait>10, you can see the effect into the graph.

[application_1.log](https://github.com/medusa-project/cantaloupe/files/2374487/application_1.log)

**Comment by adolski** [comment]
Well, I've gone over the relevant code in and around HttpSource and I don't see any leaks. Findbugs also doesn't show anything. Unfortunately I don't know of any other tools that make these easy to debug.

I think you (or someone) said this wasn't happening in 3.4.x? One of the changes in 4.0 was a Jetty update:

3.4.4 --> Jetty 9.4.7
4.0 --> Jetty 9.4.9

So that's the next place I'd look. I don't remember why I updated Jetty, but all of the tests still pass when I roll back to 9.4.7 on `release/4.0`.

The tests pass with the current version of Jetty (9.4.12) too.

(The tests don't test for leaks, of course...)

So, for 4.0.2, I could roll Jetty back, or forward. Maybe better to go back, since 9.4.7 is more proven...

**Comment by giancarlobi** [comment]
Thanks again @adolski 
New snapshot compiled and running.
I'll keep informed you what happens (or not, I hope).

**Comment by giancarlobi** [comment]
@adolski It happened again while this time without any close-wait so was not simple to detect.
What do you think if I'll try a different jetty from [maven repo](https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-util)? I think so because changing jetty version something is changed.

**Comment by adolski** [comment]
Absolutely, go for it

**Comment by giancarlobi** [comment]
@adolski I think I have good news: no more issue since Sept 20, that is 15 days.
Errors were logged due to JP2 malformed but cantaloupe no more stops retrieving remote source.
I compiled Cantaloupe with:
    <jetty.version>9.4.12.v20180830</jetty.version>
In addition I feel as Cantaloupe performance are better than previous jetty version.
I'll monitoring more days and I hope this issue was definitely solved. 
I'll check deeper logs to evaluate errors, I'll inform you.

**Comment by adolski** [comment]
That's great!

I'll update the `release/4.0` branch to that Jetty version and plan for a 4.0.2 release later this month.

Thanks for all of your help and persistence in testing this.

**Comment by adolski** [comment]
Hey @giancarlobi, are things still going well with the new Jetty?

**Comment by giancarlobi** [comment]
@adolski Yes !! all is going well, very well, so if you want close this issue for me is ok. Thanks !!

**Comment by adolski** [comment]
Awesome. Thanks again!
