### ISSUE TITLE
OpenSeadragon error "Image load aborted" on Cantaloupe processed PDF file

### ISSUE THREAD

**Issue by filak** [medusa-project/cantaloupe#247]
I have this PDF file [test7.PDF](https://github.com/medusa-project/cantaloupe/files/2557383/test7.PDF)

on Cantaloupe 4.0.2, Win7, local FilesystemSource. Full views are being rendered just fine ie. http://localhost:8182/iiif/2/test7.PDF/full/593,855/0/default.jpg

But when zooming in OSD viewer v2.4.0 (on zoom level 4, level 3 is OK), I see:

- localhost:8182/iiif/2/test7.PDF/0,855,593,854/593,/0/default.jpg:1 GET http://localhost:8182/iiif/2/test7.PDF/0,855,593,854/593,/0/default.jpg net::ERR_INCOMPLETE_CHUNKED_ENCODING
- Tile $.Tile failed to load: http://localhost:8182/iiif/2/test7.PDF/0,855,593,854/593,/0/default.jpg - error: Image load aborted

The top left tile is missing and in the error log:

2018-11-07 13:56:19,272 ERROR [qtp1690716179-146] o.r.C.Server [Slf4jLogger.java:230] An exception occurred writing the response entity
java.awt.image.RasterFormatException: negative or zero height
	at java.awt.image.Raster.<init>(Unknown Source)
	at java.awt.image.WritableRaster.<init>(Unknown Source)
	at sun.awt.image.SunWritableRaster.<init>(Unknown Source)
	at sun.awt.image.IntegerComponentRaster.<init>(Unknown Source)
	at sun.awt.image.IntegerInterleavedRaster.<init>(Unknown Source)
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(Unknown Source)
	at java.awt.image.BufferedImage.getSubimage(Unknown Source)
	at edu.illinois.library.cantaloupe.processor.Java2DUtil.crop(Java2DUtil.java:268)
	at edu.illinois.library.cantaloupe.processor.AbstractJava2DProcessor.doPostProcess(AbstractJava2DProcessor.java:275)
	at edu.illinois.library.cantaloupe.processor.AbstractJava2DProcessor.postProcess(AbstractJava2DProcessor.java:132)
	at edu.illinois.library.cantaloupe.processor.PdfBoxProcessor.process(PdfBoxProcessor.java:110)
...

I am pretty positive this did not happen in 3.4 version.  

The viewer settings:

    var viewer = OpenSeadragon({
        id: "contentDiv",
        prefixUrl: "/static/js/images/",
        tileSources: ["http://localhost:8182/iiif/2/test7.PDF/info.json"],
        debugMode: true,
        toolbar: "toolbarDiv",
        sequenceMode: true,
        showNavigator:true,
        showReferenceStrip: true,
        referenceStripScroll: 'vertical',
        preserveViewport: true,
        degrees: 0,
        showRotationControl: true,
        gestureSettingsTouch: {
            pinchRotate: false
        }
    });

**Comment by adolski** [comment]
Thanks for reporting this, @filak. Looks like a bug that was introduced in 4.0. Fix is available on `release/4.0` branch and will appear in 4.0.3.

**Comment by filak** [comment]
Another error appeared with pdf files, I do not know if the fix solved it:

2018-11-08 11:59:48,195 ERROR [qtp1690716179-33] o.r.C.Server [Slf4jLogger.java:230] An exception occurred writing the response entity
java.awt.image.RasterFormatException: (x + width) is outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(Unknown Source)
	at java.awt.image.BufferedImage.getSubimage(Unknown Source)
	at edu.illinois.library.cantaloupe.processor.Java2DUtil.crop(Java2DUtil.java:268)
	at edu.illinois.library.cantaloupe.processor.AbstractJava2DProcessor.doPostProcess(AbstractJava2DProcessor.java:275)
	at edu.illinois.library.cantaloupe.processor.AbstractJava2DProcessor.postProcess(AbstractJava2DProcessor.java:132)
	at edu.illinois.library.cantaloupe.processor.PdfBoxProcessor.process(PdfBoxProcessor.java:110)
...

**Comment by adolski** [comment]
Could you provide the URL that causes this to happen?

**Comment by filak** [comment]
This happens with [test9.pdf](https://github.com/medusa-project/cantaloupe/files/2562684/test9.pdf)

Full error log [error-log2.txt](https://github.com/medusa-project/cantaloupe/files/2562686/error-log2.txt)

**Comment by adolski** [comment]
Thanks, I believe the above commit fixes this too.

**Comment by filak** [comment]
Great! Thank you.
