### ISSUE TITLE
GraphicsMagickProcessor IOException: Broken pipe

### ISSUE THREAD

**Issue by ghohmann** [medusa-project/cantaloupe#256]
After some minutes using GM without a problem, i suddenly got an "broken pipe" error by requesting an image. I seems that GM is not able to find my images. Strange.

This is the log:
```
10:27:27.073 [qtp2051853139-43] DEBUG e.i.l.c.r.AbstractResource - Identifier requested: PT_00001_05 -> decoded: PT_00001_05 -> slashes substituted: PT_00001_05
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): not found: /data/cache/cantaloupe/info/04/bd/83/04bd830b90a1345f1bf378865179b4b4.json
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.s.FilesystemSource - Resolved PT_00001_05 to /data/media/img/arc/PT-001/PT_00001_05.jpg
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.p.ProcessorConnector - FileSource -> StreamProcessor connection between FilesystemSource and GraphicsMagickProcessor
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): not found: /data/cache/cantaloupe/info/04/bd/83/04bd830b90a1345f1bf378865179b4b4.json
10:27:27.074 [qtp2051853139-43] INFO  e.i.l.c.p.GraphicsMagickProcessor - readImageInfo(): invoking gm identify -ping -format %w%h%[EXIF:Orientation] jpg:-
10:27:27.081 [qtp2051853139-43] ERROR o.r.C.RestletApplication - Exception or error caught in server resource
```

There seems to be something wrong with the caching mechanism:
```
getImageInfo(): not found: /data/cache/cantaloupe/info/04/bd/8304bd830b90a1345f1bf378865179b4b4.json
```

When I switch back to the 'fallbackJava2dProcessor', everything works fine.
When I switch back to GM again(!), I can access the _same_ file even in other output formats.

Does anyone noticed the same behaviour?

_Originally posted by @ghohmann in https://github.com/medusa-project/cantaloupe/issues/252#issuecomment-440598950_

**Comment by ghohmann** [comment]
Additional note:
I just tried using Imagemagick instead. Works fine so far, just a bit slower.
So is this a GM problem then?

**Comment by ghohmann** [comment]
As @adolski suggested #252 here is a full log (option "trace") of an image request using GM als a jpg-processor:

```
17:14:14.724 [qtp2051853139-17] INFO  e.i.l.c.r.AbstractResource - doInit(): handling GET http://127.0.0.1:8182/iiif/2/PT_00191_01-02/full/!1024,768/0/default.jpg [Cookie: PHPSESSID=creq09g66et93jcivnh1hblfjf; Accept: image/webp,image/apng,image/*,*/*;q=0.8; Connection: keep-alive; User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36; Referer: http://127.0.0.1/dev/ptview/?do=view&id=PT_00191_01-02; Host: 127.0.0.1:8182; DNT: 1; Accept-Encoding: gzip, deflate; Accept-Language: en-US,en;q=0.9,de;q=0.8,de-DE;q=0.7]
17:14:14.725 [qtp2051853139-17] DEBUG e.i.l.c.r.AbstractResource - Identifier requested: PT_00191_01-02 -> decoded: PT_00191_01-02 -> slashes substituted: PT_00191_01-02
17:14:14.726 [qtp2051853139-17] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): not found: /data/cache/cantaloupe/info/5c/8a/7a/5c8a7a2199f4dd0454d992de08f4e102.json
17:14:14.726 [qtp2051853139-17] INFO  e.i.l.c.s.FilesystemSource - Resolved PT_00191_01-02 to /data/media/img/arc/PT-001/PT_00191_01-02.jpg
17:14:14.726 [qtp2051853139-17] INFO  e.i.l.c.p.ProcessorConnector - FileSource -> StreamProcessor connection between FilesystemSource and GraphicsMagickProcessor
17:14:14.726 [qtp2051853139-17] INFO  e.i.l.c.c.FilesystemCache - getImageInfo(): not found: /data/cache/cantaloupe/info/5c/8a/7a/5c8a7a2199f4dd0454d992de08f4e102.json
17:14:14.726 [qtp2051853139-17] INFO  e.i.l.c.p.GraphicsMagickProcessor - readImageInfo(): invoking gm identify -ping -format %w%h%[EXIF:Orientation] jpg:-
17:14:14.737 [qtp2051853139-17] ERROR o.r.C.RestletApplication - Exception or error caught in server resource
org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:527)
        at org.restlet.resource.ServerResource.get(ServerResource.java:723)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
        at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)
        at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
        at org.restlet.resource.ServerResource.handle(ServerResource.java:1020)
        at org.restlet.resource.Finder.handle(Finder.java:236)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
        at org.restlet.Application.handle(Application.java:385)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.routing.Router.doHandle(Router.java:422)
        at org.restlet.routing.Router.handle(Router.java:641)
        at org.restlet.routing.Filter.doHandle(Filter.java:150)
        at org.restlet.routing.Filter.handle(Filter.java:197)
        at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
        at org.restlet.Component.handle(Component.java:408)
        at org.restlet.Server.handle(Server.java:507)
        at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: Broken pipe
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:355)
        at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
        at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
        at edu.illinois.library.cantaloupe.process.Pipe.copyBytes(Pipe.java:80)
        at edu.illinois.library.cantaloupe.process.Pipe.provideInput(Pipe.java:45)
        at edu.illinois.library.cantaloupe.process.ProcessStarter.processInput(ProcessStarter.java:37)
        at edu.illinois.library.cantaloupe.process.ProcessStarter.waitForProcess(ProcessStarter.java:121)
        at edu.illinois.library.cantaloupe.process.ProcessStarter.run(ProcessStarter.java:80)
        at edu.illinois.library.cantaloupe.processor.GraphicsMagickProcessor.readImageInfo(GraphicsMagickProcessor.java:489)
        at edu.illinois.library.cantaloupe.cache.InfoService.readInfo(InfoService.java:199)
        at edu.illinois.library.cantaloupe.cache.InfoService.getOrReadInfo(InfoService.java:135)
        at edu.illinois.library.cantaloupe.cache.CacheFacade.getOrReadInfo(CacheFacade.java:67)
        at edu.illinois.library.cantaloupe.resource.AbstractResource.getOrReadInfo(AbstractResource.java:456)
        at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:157)
        at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
        ... 69 common frames omitted
17:14:14.737 [qtp2051853139-17] DEBUG e.i.l.c.r.AbstractResource - X-Forwarded headers: Proto: http; Host: null; Port: null; Path:
17:14:14.738 [qtp2051853139-17] DEBUG e.i.l.c.r.AbstractResource - Base URI assembled: http://127.0.0.1:8182
```

**Comment by adolski** [comment]
Thanks for creating this issue, @ghohmann. Like you said, this doesn't happen with most images, but I was able to find one that caused it. I believe there is an issue with `gm` whereby it sometimes prematurely closes its stdin.

I can think of a workaround that should fix this when using FilesystemSource, but not sure if there is anything I can do about other sources.
