### ISSUE TITLE
kdu_jni

### ISSUE THREAD

**Issue by vruchtvet** [medusa-project/cantaloupe#259]
Hi,

I installed cantaloupe-4.0.2.war in my webaps directory (as cantaloupe.war). jpg and tif files are served ok, jp2 files give me an internal server error (see below)
Do i need to install additional jars?

Regards,
Hans Scholte

500 Internal Server Error
kdu_jni (Not found in java.library.path)

java.lang.UnsatisfiedLinkError: kdu_jni (Not found in java.library.path)
	at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1428)
	at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1398)
	at java.lang.System.loadLibrary(System.java:569)
	at kdu_jni.Kdu_global.<clinit>(Kdu_global.java:5)
	at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.initializeClass(KakaduNativeProcessor.java:268)
	at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.getInitializationException(KakaduNativeProcessor.java:286)
	at edu.illinois.library.cantaloupe.processor.ProcessorFactory.newProcessor(ProcessorFactory.java:62)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
	at org.restlet.resource.ServerResource.get(ServerResource.java:723)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
	at org.restlet.resource.ServerResource.doNegotiatedHandle

**Comment by adolski** [comment]
Hi @vruchtvet ,

Please see [here](https://medusa-project.github.io/cantaloupe/manual/4.0/processors.html#KakaduNativeProcessor) for steps to get KakaduNativeProcessor working.

**Comment by jamesberes** [comment]
Hello, I'm having this issue with 4.1.2 when loading jp2 images
processor.jp2 = OpenJpegProcessor
OpenJpegProcessor.path_to_binaries = /prod/dependencies/openjpeg/bin
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class kdu_jni.Jpx_source
	at edu.illinois.library.cantaloupe.processor.codec.JPEG2000KakaduImageReader.<init>(JPEG2000KakaduImageReader.java:190)
	at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.<init>(KakaduNativeProcessor.java:129)
```

but your link for getting it to work returns a 404

**Comment by adolski** [comment]
Hi @jamesberes ,

I'm not sure what is happening here -- there shouldn't be any Kakadu-related code being executed when you are using OpenJpegProcessor. I updated the link above, but I don't know if it's relevant. Please open a new issue for this if it continues to be a problem.

**Comment by lguariento** [comment]
Hello, this happens to me too (cantaloupe 4.1.7, starting it with `java -Dcantaloupe.config=cantaloupe.properties -Xmx2g -jar cantaloupe-4.1.7.war`).

I have

`processor.ManualSelectionStrategy.jp2 = OpenJpegProcessor`

in my cantalopue.properties and I get

```
Caused by: java.lang.UnsatisfiedLinkError: no kdu_jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at kdu_jni.Kdu_message.<clinit>(Kdu_message.java:5)
	at edu.illinois.library.cantaloupe.processor.codec.JPEG2000KakaduImageReader.<clinit>(JPEG2000KakaduImageReader.java:193)
	at edu.illinois.library.cantaloupe.processor.KakaduNativeProcessor.<init>(KakaduNativeProcessor.java:129)
```
