### ISSUE TITLE
Java2dProcessor exception: Inconsistent metadata read from stream

### ISSUE THREAD

**Issue by adolski** [medusa-project/cantaloupe#46]
Version: 3.3-SNAPSHOT

URL: https://iiif-dev.library.illinois.edu/dls/iiif/2/378%2F2259%2F2620076%2Faccess%2Fonline%2F32nd+Armored+Regiment+Photo+and+War+Diary%2F32nd+Regiment+D+Company.jpg/square/!256,256/0/default.jpg

Medusa pathname: /378/2259/2620076/access/online/32nd Armored Regiment Photo and War Diary/32nd Regiment D Company.jpg

```
java.io.IOException: edu.illinois.library.cantaloupe.processor.ProcessorException: Inconsistent metadata read from stream
    at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:139)
    at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:90)
    at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
    at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
    at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
    at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
    at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
    at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
    at org.eclipse.jetty.server.Server.handle(Server.java:524)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
    at java.lang.Thread.run(Thread.java:745)
Caused by: edu.illinois.library.cantaloupe.processor.ProcessorException: Inconsistent metadata read from stream
    at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:222)
    at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:132)
    ... 31 common frames omitted
Caused by: javax.imageio.IIOException: Inconsistent metadata read from stream
    at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:362)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1023)
    at edu.illinois.library.cantaloupe.processor.imageio.JpegImageReader.getMetadata(JpegImageReader.java:37)
    at edu.illinois.library.cantaloupe.processor.imageio.ImageReader.getMetadata(ImageReader.java:134)
    at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:219)
    ... 32 common frames omitted
```

**Comment by adolski** [comment]
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6355567

**Comment by adolski** [comment]
Not sure what I even did, but it's working in 3.3-SNAPSHOT.

**Comment by DiegoPino** [comment]
We are observing this issue again on latest (develop) built 5 days ado (Jan 8th 2024).

This is the output of ExifTool 

```
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : inches
X Resolution                    : 200
Y Resolution                    : 200
Comment                         : Image produced by nextScan nsOutput version: 2.8
Image Width                     : 832
Image Height                    : 1800
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 1
Image Size                      : 832x1800
Megapixels                      : 1.5
```

These are all Grey scale images (Microfilm scans)

**Comment by DiegoPino** [comment]
There are plenty documented/related issues with Java2D googling when processing JFIF via ::readAll() (seems related to the occurrence/location of APP0?). Someone suggests that https://github.com/haraldk/TwelveMonkeys#jpeg is a (well maintained) in place replacement for ImageIO with API compatibility for most generic cases (as we do in Cantaloupe) that is a little bit more forgiving. The larger issue here is that when this fails info.json generate errors, but the image/tiles can actually be delivered. @glenrobson @jcoyne any one has strong opinions about e.g giving TwelveMokeys Libraries a try? Or logs are simply full of warnings/errors. One added benefit is that TwelveMokeys library could also process HDR (opens future possibilities?)

**Comment by jcoyne** [comment]
@DiegoPino that certainly sounds like something worth investigating.

**Comment by DiegoPino** [comment]
@jcoyne thanks. I will open a follow up issue and give some testing + a pull a try. Thanks!
