### ISSUE TITLE
ProcessorException: Illegal band size for 16 bit TIFF images

### ISSUE THREAD

**Issue by imoutsatsos** [medusa-project/cantaloupe#49]
Working with 16 bit gray scale TIFF scientific images, I get an `ProcessorException: Illegal band size: should be 0 < size <= 8`

Attached is an example that can be used for testing here:
[AF41.zip](https://github.com/medusa-project/cantaloupe/files/520422/AF41.zip)

![image](https://cloud.githubusercontent.com/assets/3408226/19250926/cfa45852-8f0a-11e6-83d5-04ca67e4973d.png)

The Error Trace
16:41:04.114 [qtp1349277854-12] INFO  e.i.l.c.resource.SourceImageWrangler - FileResolver -> FileProcessor connection between FilesystemReso lver and Java2dProcessor
16:41:04.114 [qtp1349277854-12] INFO  e.i.l.c.resolver.FilesystemResolver - Resolved /VB00045122_1/AF41.tif to D:\DEVTOOLS\Jenkins\userContent\pictures\VB00045122_1\AF41.tif
16:41:04.130 [qtp1349277854-12] INFO  e.i.l.c.p.imageio.TiffImageReader - createReader(): using it.geosolutions.imageioimpl.plugins.tiff.TIF FImageReader
16:41:04.130 [qtp1349277854-12] DEBUG e.i.l.c.resource.AbstractResource - Read info of /VB00045122_1/AF41.tif in 0 msec
16:41:04.130 [qtp1349277854-12] DEBUG e.i.l.c.resource.AbstractResource - isAuthorized(): delegate script is disabled; allowing.
16:41:04.145 [qtp1349277854-12] DEBUG e.i.l.c.resource.AbstractResource - addNonEndpointOperations(): redactions are disabled; skipping.
16:41:04.145 [qtp1349277854-12] DEBUG e.i.l.c.resource.AbstractResource - addNonEndpointOperations(): watermarking is disabled; skipping.
16:41:04.145 [qtp1349277854-12] DEBUG e.i.l.c.resource.AbstractResource - Read info of /VB00045122_1/AF41.tif in 0 msec
16:41:04.145 [qtp1349277854-12] DEBUG e.i.l.c.p.i.AbstractImageReader - tileAwareRead(): acquiring region 0,0/1024x1024 from 1024x1024 image

16:41:04.176 [qtp1349277854-12] DEBUG e.i.l.c.p.i.AbstractImageReader - readSmallestUsableSubimage(): using a 1024x1024 source image (0x red uction factor)
16:41:04.192 [qtp1349277854-12] ERROR org.restlet.Component.Server - An exception occurred writing the response entity
java.io.IOException: edu.illinois.library.cantaloupe.processor.ProcessorException: Illegal band size: should be 0 < size <= 8
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:139)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.write(ImageRepresentation.java:90)
        at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:513)
        at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:457)
        at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:421)
        at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
        at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
        at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Unknown Source)
Caused by: edu.illinois.library.cantaloupe.processor.ProcessorException: Illegal band size: should be 0 < size <= 8
        at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:222)
        at edu.illinois.library.cantaloupe.resource.ImageRepresentation.doWrite(ImageRepresentation.java:132)
        ... 31 common frames omitted
Caused by: javax.imageio.IIOException: Illegal band size: should be 0 < size <= 8
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(Unknown Source)
        at edu.illinois.library.cantaloupe.processor.imageio.JpegImageWriter.write(JpegImageWriter.java:134)
        at edu.illinois.library.cantaloupe.processor.imageio.ImageWriter.write(ImageWriter.java:59)
        at edu.illinois.library.cantaloupe.processor.Java2dProcessor.process(Java2dProcessor.java:220)
        ... 32 common frames omitted

**Comment by adolski** [comment]
Thanks for reporting this. As a temporary workaround, you might try setting `processor.tif` to something else that supports TIFFs, like JaiProcessor. (Also GraphicsMagickProcessor or ImageMagickProcessor if those libraries are installed and the TIFFs aren't very big.)

**Comment by adolski** [comment]
I've committed some code that enables >8-bit images in Java2dProcessor, ImageMagickProcessor, and GraphicsMagickProcessor. (Still need to work on JaiProcessor.) If you are able to check out the repository and build it (`$ mvn package -Dmaven.test.skip=true`), you will find the resulting .war file located at `target/Cantaloupe-3.3-SNAPSHOT.war` and it will work with your existing configuration file. However,

Although this image is 16-bit, it appears to not be using most of that range, so in order to achieve the appearance of the benchmark JPEG you posted, its levels need to be normalized. Simply scaling the levels down into 8 bits will result in a dark image. I am wary about implementing an "auto-levels" feature, although maybe it could work as a configuration option.

I haven't done much work with 16-bit images, as the repository I work with does not contain any. But, the APIs used by Cantaloupe offer a lot of control, so it should be possible to improve the support for these, and I would like to.

**Comment by imoutsatsos** [comment]
Great progress! I've already followed you previous recommendation to set ```processor.tif=JaiProcessor``` and indeed I can serve the image with no errors. Same as you've noticed though, the image appears 'overexposed'
![image](https://cloud.githubusercontent.com/assets/3408226/19282075/bd6ae650-8fba-11e6-8cb6-b50b86267436.png)

I agree with you that 'auto-leveling' is tricky especially when you want to compare images for intensity features (quite frequent in digital microscopy) We have faced the issue and typically we opt for UI controls to compensate for such situations ([example here](http://www.microscopesinternational.com/deepzoom/mxii60-kidney.aspx)). Still, it would be nice if there was an Image API component that can deal with such image adjustments.  The Image API already support rotation and such so why not brightness and contrast?

Anyway, let me know if I can provide additional images for testing. I have some images that due to pure contrast they do not display at all now with the default settings. Here is a sample:
[AF041_FITC.zip](https://github.com/medusa-project/cantaloupe/files/522583/AF041_FITC.zip)

I will also try to give the new war file a try before finishing this evaluation round. 
Thanks for all your help.

Best regards
Ioannis

**Comment by adolski** [comment]
Yes, it's too bad that there is no support for level adjustment in the Image API. IIIF came out of the library world where that feature is not needed very often, and I have been reluctant to add it "on top of" the Image API, as it would have to be done in a non-standard way, something like `/full/full/0/default.jpg?brightness=&contrast=`...

If it would help you, auto-leveling can be added very easily to ImageMagickProcessor and GraphicsMagickProcessor (of course I would want to make it optional). This could work if your images remain not much bigger than 1024x1024, but it still wouldn't give you client-side adjustments.

I do know that the IIP protocol would get you these features. Then you would have to look into an image server that supports that protocol, like IIPImage.

Anyway, I just added 16-bit source support to JaiProcessor, but it works the same way as the others (linear pixel rescaling), so it won't help in this case.

**Comment by imoutsatsos** [comment]
In my case the majority of the images are 1024x1024. Having auto-leveling as optional would work. Are you thinking of setting this in the configuration file? Or somehow image driven? Let's say if the intensity histogram has certain characteristics?

**Comment by adolski** [comment]
I don't think ImageMagick supports that kind of conditional level adjustment. But, if you can pull down the latest code and build the project as above, and then set `processor.tif = ImageMagickProcessor` and add `ImageMagickProcessor.auto_levels = true` to your configuration file, it should work. (Of course, you will need to have ImageMagick installed.)

I may add this feature to more processors, if possible, but it will have to wait a while. I looked into adding to GraphicsMagickProcessor as well, but apparently GM doesn't support auto-levels as I thought it did.

Hope this helps!

**Comment by imoutsatsos** [comment]
Hi Alex;

Thanks for releasing the new snapshot! I'm now trying to execute it Cantaloupe-3.3SNAPSHOT.war and getting an error: The maven build was successful. 

```C:\Imaging\Cantaloupe-3.2>java -Dcantaloupe.config=.\cantaloupe.properties -Xmx2g -jar Cantaloupe-3.3-SNAPSHOT.war
Exception in thread "main" java.lang.NoClassDefFoundError: edu/illinois/library/cantaloupe/config/ConfigurationWatcher
        at edu.illinois.library.cantaloupe.config.FileConfiguration.<init>(FileConfiguration.java:11)
        at edu.illinois.library.cantaloupe.config.PropertiesConfiguration.<init>(PropertiesConfiguration.java:11)
        at edu.illinois.library.cantaloupe.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:31)
        at edu.illinois.library.cantaloupe.StandaloneEntry.main(StandaloneEntry.java:37)
Caused by: java.lang.ClassNotFoundException: edu.illinois.library.cantaloupe.config.ConfigurationWatcher
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more```

**Comment by adolski** [comment]
Whoops, sorry about that -- it should build now.

**Comment by imoutsatsos** [comment]
Alex, thanks for fixing the Cantaloupe-3.3-SNAPSHOT release! 
I'm now successful in launching Cantaloupe, however I'm having trouble with the ImageMagick TIFF support. I'm on Windows, so I've downloaded and installed the most recent version of ImageMagick. It is in my PATH variable and I can execute ```magick``` commands. I have used this same path in the cantaloupe.properties file. So the ImageMagickProcessor settings are:
```
processor.tif = ImageMagickProcessor
processor.webp = ImageMagickProcessor
ImageMagickProcessor.path_to_binaries = D:/UTILS/ImageMagick/ImageMagick-7.0.3-Q16
ImageMagickProcessor.sharpen = 0
ImageMagickProcessor.background_color = black
ImageMagickProcessor.auto_levels = true 
```
However, when I try to serve a TIF image I always get the following exceptions. I do not think that Cantaloupe is finding the ImageMagick executable.
```
edu.illinois.library.cantaloupe.processor.UnsupportedSourceFormatException: ImageMagickProcessor does not support the TIFF source format
	at edu.illinois.library.cantaloupe.processor.AbstractProcessor.setSourceFormat(AbstractProcessor.java:24)
	at edu.illinois.library.cantaloupe.processor.ProcessorFactory.getProcessor(ProcessorFactory.java:59)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.ImageResource.doGet(ImageResource.java:111)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:523)
	at org.restlet.resource.ServerResource.get(ServerResource.java:742)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:617)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:678)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:356)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1043)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Unknown Source)
```

What do you think is happening?

Thanks and best regards
Ioannis

**Comment by adolski** [comment]
Hi Ioannis,

Are you sure that the ImageMagick TIFF delegate is installed? If you invoke a command like `identify image.tif`, does it work, or do you see an error message like, `identify: no decode delegate for this image format `TIFF'`?

**Comment by imoutsatsos** [comment]
Yes I think this is working although the reality is I don't know much about delegates ;-)
```
D:\DEVTOOLS\Jenkins\userContent\pictures\VB00045122_1>magick identify AF41.tif
AF41.tif TIFF 1024x1024 1024x1024+0+0 16-bit Grayscale Gray 2.098MB 0.016u 0:00.015
identify: Unknown field with tag 65400 (0xff78) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/905.
```

**Comment by adolski** [comment]
Thank you for helping out with the Windows testing. ;)

ImageMagickProcessor is written against ImageMagick 6.x. Apparently the "magick" command in 7 replaces "convert" and "identify" from 6.x. Just to be sure, during the ImageMagick 7 install, you need to make sure the "Install legacy utilities (e.g. convert)" checkbox is checked.

Aside from that, I did find a bug affecting paths on Windows. I've pushed a commit that ought to fix it, and now I am able to view your TIFF file using ImageMagickProcessor with ImageMagick 7.0.3 in Windows, and my `ImageMagickProcessor.path_to_binaries` key set just like yours.

**Comment by imoutsatsos** [comment]
Awesome! Can't wait to try it tomorrow!

**Comment by imoutsatsos** [comment]
Alex, Cantaloupe works great now! I build the new snapshot, installed the ImageMagick 'legacy utilities' and retried the ImageMagickProcessor. I can now display the 16bit TIFF files and can also 'auto-level' the brightness. Lots of functionality packed into Cantaloupe!!

One of my current interests is building scientific workflows and utilities using the continous integration tool Jenkins. So, here is  a screenshot of  Cantaloupe, OpensSeadragon, Jenkins working together to create a digital microscope image viewer widget.

Thanks for all your help! I will continue exploring and using Cantaloupe so you'll hear from me soon again.

Cheers
Ioannis

![image](https://cloud.githubusercontent.com/assets/3408226/19365164/77155b9e-915f-11e6-92a6-3d5b64754a5c.png)

**Comment by adolski** [comment]
Great news! Glad you are finding it useful.

BTW, I have created some issues for adding the auto-levels feature to other processors: #54, #55, #56, #57.

**Comment by adolski** [comment]
Just wanted to give you a heads-up that I have replaced the `ImageMagickProcessor.auto_levels` key with `ImageMagickProcessor.normalize`, which applies a similar but simpler contrast-stretch operation.

Also, `GraphicsMagickProcessor.normalize` and `Java2dProcessor.normalize` are now available.

**Comment by adolski** [comment]
Hi @imoutsatsos, just to let you know, I decided to consolidate the `ImageMagickProcessor.normalize` config key (along with the other `*.normalize` keys) into `processor.normalize` so that it applies to all processors.

Didn't want you to do a pull and wonder why it stopped working!

**Comment by imoutsatsos** [comment]
Excellent. Thanks for the heads up!!
