### ISSUE TITLE
Caching - file does not exist error  (follow-up to #66)

### ISSUE THREAD

**Issue by FrancoisPaquette** [medusa-project/cantaloupe#74]
Hi,

I would like to add to four observations to issue #66, maybe it is going to help.

1.  When we get this error, we are not getting back the image from the server.

11:46:23.991 [Finalizer] [39mDEBUG[0;39m [37me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - Moving /var/cantaloupe/cache/image/06/cc/30/Vy634GAYItswXF3iow7CVg_140%2C.jpg.tmp to Vy634GAYItswXF3iow7CVg_140%2C.jpg
11:46:23.991 [Finalizer] [31mWARN [0;39m [36me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - edu.illinois.library.cantaloupe.cache.FilesystemCache$ConcurrentFileOutputStream.close(): Source '/var/cantaloupe/cache/image/06/cc/30/Vy634GAYItswXF3iow7CVg_140%2C.jpg.tmp' does not exist
11:46:23.991 [Finalizer] [39mDEBUG[0;39m [37me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - Closing stream for Vy634GAYItswXF3iow7CVg_scale:140,.jpg

2. It only happen when we ask for the server to modify the size of the image.

3. We also get server error related to the same error.

11:44:54.433 [http-nio-8080-exec-8] [39mDEBUG[0;39m [37me.i.l.c.cache.FilesystemCache[0;39m - putImageInfo(): moving /var/cantaloupe/cache/info/04/1a/96/pDmEAiUfoAQ6EVUKSNCaoA.json.tmp to pDmEAiUfoAQ6EVUKSNCaoA.json
28-Nov-2016 11:44:54.434 SEVERE [http-nio-8080-exec-9] org.restlet.resource.ServerResource.doCatch Exception or error caught in server resource
 org.restlet.resource.ResourceException: Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:539)
	at org.restlet.resource.ServerResource.get(ServerResource.java:742)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:617)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:678)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:356)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1043)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: edu.illinois.library.cantaloupe.cache.CacheException: Unable to create /var/cantaloupe/cache/info/04/1a/96/pDmEAiUfoAQ6EVUKSNCaoA.json.tmp
	at edu.illinois.library.cantaloupe.cache.FilesystemCache.putImageInfo(FilesystemCache.java:983)
	at edu.illinois.library.cantaloupe.resource.AbstractResource.getOrReadInfo(AbstractResource.java:382)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGet(InformationResource.java:103)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:523)
	... 64 more
Caused by: java.io.IOException: Unable to create /var/cantaloupe/cache/info/04/1a/96/pDmEAiUfoAQ6EVUKSNCaoA.json.tmp
	at edu.illinois.library.cantaloupe.cache.FilesystemCache.putImageInfo(FilesystemCache.java:980)
	... 70 more
Caused by: java.io.IOException: File '/var/cantaloupe/cache/info/04/1a/96/pDmEAiUfoAQ6EVUKSNCaoA.json.tmp' cannot be written to
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:357)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1962)
	at edu.illinois.library.cantaloupe.cache.FilesystemCache.putImageInfo(FilesystemCache.java:972)
	... 70 more

4. We had quite a few errors at 1:37 AM the 25th, here's an example.

01:37:19.521 [Finalizer] [39mDEBUG[0;39m [37me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - Moving /var/cantaloupe/cache/image/2f/0b/de/E5MxmcqvGN1RybGn7TBNKw_200%2C.jpg.tmp to E5MxmcqvGN1RybGn7TBNKw_200%2C.jpg
01:37:19.525 [Finalizer] [31mWARN [0;39m [36me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - edu.illinois.library.cantaloupe.cache.FilesystemCache$ConcurrentFileOutputStream.close(): Source '/var/cantaloupe/cache/image/2f/0b/de/E5MxmcqvGN1RybGn7TBNKw_200%2C.jpg.tmp' does not exist
01:37:19.526 [Finalizer] [39mDEBUG[0;39m [37me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - Closing stream for E5MxmcqvGN1RybGn7TBNKw_scale:200,.jpg

But the call to the server was done the day before and it looks like every fine.

24-Nov-2016 17:51:37.963 INFO [http-nio-8080-exec-7] org.restlet.engine.log.LogFilter.afterHandle 2016-11-24	17:51:37	0:0:0:0:0:0:0:1	-	0:0:0:0:0:0:0:1	80	GET	/iiif/2/E5MxmcqvGN1RybGn7TBNKw/full/200,/0/default.jpg	-	200	-	0	79	http://dvlimg0a.bnquebec.ca	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36	http://localhost:3000/patrimoine/details/52327/2386031
17:51:37.963 [http-nio-8080-exec-7] [34mINFO [0;39m [37me.i.l.c.cache.FilesystemCache[0;39m - getImageOutputStream(OperationList): miss; caching E5MxmcqvGN1RybGn7TBNKw_scale:200,.jpg
17:51:37.964 [http-nio-8080-exec-7] [39mDEBUG[0;39m [37me.i.l.c.p.i.AbstractImageReader[0;39m - createReader(): ignoring metadata? true
17:51:37.965 [http-nio-8080-exec-7] [34mINFO [0;39m [37me.i.l.c.p.i.AbstractImageReader[0;39m - createReader(): using com.sun.imageio.plugins.jpeg.JPEGImageReader
17:51:38.054 [http-nio-8080-exec-7] [39mDEBUG[0;39m [37me.i.l.cantaloupe.processor.JaiUtil[0;39m - scaleImage(): width: 14.174344436569807%; height: 14.149999999999999%
17:51:38.110 [http-nio-8080-exec-7] [39mDEBUG[0;39m [37me.i.l.c.resource.ImageRepresentation[0;39m - JaiProcessor processed in 146 msec: E5MxmcqvGN1RybGn7TBNKw_scale:200,.jpg
17:51:38.110 [http-nio-8080-exec-7] [39mDEBUG[0;39m [37me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - Moving /var/cantaloupe/cache/image/2f/0b/de/E5MxmcqvGN1RybGn7TBNKw_200%2C.jpg.tmp to E5MxmcqvGN1RybGn7TBNKw_200%2C.jpg
17:51:38.110 [http-nio-8080-exec-7] [39mDEBUG[0;39m [37me.i.l.c.c.FilesystemCache$ConcurrentFileOutputStream[0;39m - Closing stream for E5MxmcqvGN1RybGn7TBNKw_scale:200,.jpg

Have you seen this before?

Thanks!
Frank

**Comment by kinow** [comment]
Chiming in :-)

>Caused by: java.io.IOException: File '/var/cantaloupe/cache/info/04/1a/96/pDmEAiUfoAQ6EVUKSNCaoA.json.tmp' cannot be written to

Could you be that the cache, or some other folder, is full, or with wrong permissions? Maybe it changed since the last time it worked?

If you have control of the server, you may try impersonating the user (i.e. something like su - leuserrunningjava -s /bin/bash), and trying to create an empty text in the same folder, or maybe creating a folder in one of the folders in the exception log.

That would at least eliminate any chance of restrictions in your server/environment.

**Comment by FrancoisPaquette** [comment]
Hi,
Thanks for your input, it is appreciated.

To answer your questions, there is plenty of space on the server and the permissions are fines.  If I send a call manually to the server, there is no problem at all.  It happens when the calls come from Open SeaDragon.  We are not sure yet were the issue is coming from yet, 

Thanks

**Comment by adolski** [comment]
It looks like a bug in OpenSeadragon has uncovered a bug in FilesystemCache. When I load a test JP2 in OSD, it makes 7 pseudo-simultaneous image HTTP requests, but Cantaloupe (3.2.1) only creates 6 cached images, because two of the requests are identical. One of them succeeds and the other gets an HTTP 500 response.

It happens only when caching is enabled and sometimes it doesn't happen. Also, there are some log messages coming from the finalizer that shouldn't be. Another bug.

Anyway, thanks for reporting this. I believe it is now fixed in the `release/3.2` branch (tracking 3.2.2), and has been merged into `develop` (tracking 3.3). If you want, you can build a snapshot (`git checkout release/3.2; mvn package -Dmaven.test.skip=true`) that will work with your current config file.
